# -*- coding: utf-8 -*-
"""Deutsch — Sie. Keine „Geheimtipp“, „atemberaubend“, „malerisch“, „Muss“."""

G = [
    ("P0", "golden-circle", "Golden Circle ab Reykjavík", "Þingvellir, Geysir und Gullfoss an einem Tag — selbst fahren oder Tour."),
    ("P0", "blue-lagoon", "Blue Lagoon: Tickets und Transfer", "Wie Sie es um Ihre Flüge legen — und ob der Preis stimmt."),
    ("P0", "nordlichter-reykjavik", "Nordlichter in und um Reykjavík", "Saison, Vorhersage, Plätze in der Stadt, und wann eine Tour wirklich hilft."),
    ("P0", "hallgrimskirkja", "Hallgrímskirkja und der Turm", "Die Kirche, der Aufzug, die Schlange, und wann Sie hochfahren sollten."),
    ("P0", "flughafen-keflavik-reykjavik", "Vom Flughafen Keflavík in die Stadt", "Flybus, Privattransfer, Mietwagen — Kosten und Zeit im Vergleich."),
    ("P0", "sky-lagoon", "Sky Lagoon", "Die Thermallagune am Stadtrand und ihr siebenstufiges Ritual."),
    ("P0", "walbeobachtung-reykjavik", "Wale und Papageitaucher", "Boote ab dem alten Hafen, Saisonzeiten und Seekrankheit."),
    ("P0", "beste-reisezeit-reykjavik", "Beste Reisezeit für Reykjavík", "Tageslicht, Nordlichter, Wetter und Preise, Monat für Monat."),
    ("P0", "ein-tag-in-reykjavik", "Ein Tag in Reykjavík", "Die Route zu Fuß, in die das Wesentliche an einem Tag passt."),
    ("P0", "reykjavik-sehenswuerdigkeiten", "Reykjavík Sehenswürdigkeiten", "Die vollständige Liste — sortiert danach, was Ihre knappen Tagesstunden wert ist."),
    ("P1", "golden-circle-mietwagen-oder-tour", "Golden Circle: Mietwagen oder Tour?", "Ehrlicher Vergleich nach Kosten und Zeit."),
    ("P1", "tagesausfluege-ab-reykjavik", "Tagesausflüge ab Reykjavík", "Jeder Ausflug, der sich lohnt — mit Fahrzeiten."),
    ("P1", "suedkueste-island", "Südküste an einem Tag", "Seljalandsfoss, Skógafoss und der schwarze Strand Reynisfjara."),
    ("P1", "sun-voyager", "Sun Voyager und die Uferpromenade", "Die meistfotografierte Skulptur der Stadt — und was sie wirklich darstellt."),
    ("P1", "harpa", "Konzerthaus Harpa", "Die gläserne Wabe, und wie sie den Crash überstand."),
    ("P1", "alter-hafen-reykjavik", "Der alte Hafen", "Boote, Essen, das Küstenwachschiff und die Kabeljaukriege."),
    ("P1", "regenbogenstrasse-laugavegur", "Regenbogenstraße und Laugavegur", "Die bemalte Gasse und die Haupteinkaufsstraße."),
    ("P1", "perlan", "Perlan", "Die Kuppel, die Eishöhle und die Aussichtsplattform."),
    ("P1", "zwei-tage-in-reykjavik", "Zwei Tage in Reykjavík", "Ein ruhigerer Plan, mit Platz für eine Lagune."),
    ("P1", "packliste-island", "Packliste und Kleidung", "Schichten, die halten, wenn das Wetter stündlich wechselt."),
    ("P1", "fortbewegung-reykjavik", "Fortbewegung in Reykjavík", "Zu Fuß, mit dem Strætó-Bus, und wann Sie ein Auto brauchen."),
    ("P1", "reykjavik-preise", "Ist Reykjavík teuer?", "Was die Dinge wirklich kosten — und wo Sie sparen."),
    ("P1", "unterkunft-reykjavik", "Wo in Reykjavík wohnen", "Die Viertel erklärt, und was Sie für jedes zahlen."),
    ("P2", "street-art-reykjavik", "Street Art in Reykjavík", "Die Wandbilder — samt dem Vampir, den niemand erklärt."),
    ("P2", "grotta-leuchtturm", "Grótta und die besten Nordlicht-Plätze", "Wohin Sie sich stellen, wenn der Himmel grün wird."),
    ("P2", "tjoernin-austurvoellur-parlament", "Tjörnin, Austurvöllur und das Alþingi", "Der Teich, der Platz und das älteste Parlament der Welt."),
    ("P2", "islaendische-kueche", "Isländische Küche", "Pylsa, Skyr, Lammsuppe, Hákarl — was Sie probieren und was Sie lassen sollten."),
    ("P2", "thermalbaeder-reykjavik", "Thermalbäder und Baderegeln", "Die Duschregeln, vor denen niemand die Touristen warnt."),
    ("P2", "reykjavik-kostenlos", "Reykjavík zum Nulltarif", "Ein ganzer Tag, der nichts kostet."),
    ("P2", "museen-reykjavik", "Museen in Reykjavík", "Nationalmuseum, Ausstellung 871±2 — und die schrägen."),
]

CONTENT = {
    "slugs": {"guides": "guides", "privacy": "datenschutz",
              "affiliate": "affiliate-hinweis"},
    "guides": [{"wave": w, "slug": s, "title": t, "desc": d} for w, s, t, d in G],

    "ui": {
        "menu": "Guides", "menu_all": "Alle Guides",
        "buy": "Audioguide kaufen — 9,99 €",
        "see_tours": "Touren ansehen", "check_tickets": "Tickets ansehen",
        "sticky_title": "Reykjavík City Walking Tour — 9,99 €",
        "sticky_sub": "4,7 ★ · 27 Stationen · offline · auf Englisch",
        "sticky_btn": "Jetzt kaufen",
        "rating_aria": "Bewertet mit 4,7 von 5",
        "rating_label": "Durchschnittsbewertung",
        "price_display": "9,99 €",
        "price_sub": "Einmalzahlung · kein Abo · 1 Jahr Zugriff",
        "checkout_note": "Sichere Zahlung auf dieser Seite. Lieber im Shop?",
        "open_shop": "Bei TouringBee öffnen",
        "audio_fallback": "Ihr Browser kann kein Audio abspielen.",
        "product_name": "Reykjavík City Walking Tour",
        "product_name_full": "Reykjavík City Walking Tour — Audioguide auf eigene Faust",
        "product_desc": "Ein Stadtrundgang durch Reykjavík auf eigene Faust mit 27 Stationen, Offline-Audio und Offline-GPS-Karte — vom Ingólfur-Arnarson-Denkmal bis Þúfa. Rund 2 bis 2,5 Stunden.",
        "product_category": "Audioguide auf eigene Faust",
        "author_h": "Über den Autor",
        "author_alt": "Eugene, Autor der TouringBee-Audioguides",
        "author_bio": "Eugene lebt seit sechzehn Jahren in Frankreich, hat als Guide gearbeitet und das Reise-Content-Netzwerk paris10.travel gegründet. Er war in über 300 französischen Städten und Dörfern und schreibt die TouringBee-Audioguides. Diese Guides baut er so, wie er einen Freund vor der Reise briefen würde: was Ihre Zeit wirklich wert ist, was Sie buchen sollten und was Sie auslassen können.",
        "author_bio_plain": "Ehemaliger Guide, Gründer von paris10.travel, Autor der TouringBee-Audioguides.",
        "f_explore": "Entdecken", "f_product": "Der Audioguide", "f_legal": "Rechtliches",
        "f_langs": "Sprachen", "f_alltours": "Alle TouringBee-Touren",
        "f_terms": "AGB",
        "langnames": {"en": "English", "fr": "Français", "de": "Deutsch", "es": "Español",
                      "it": "Italiano", "pt": "Português", "pl": "Polski", "ru": "Русский"},
        "disclaimer": "reykjavikwalk.com wird herausgegeben von Touringbee Limited (Irland, Firmennummer 660321). Einige Links auf dieser Seite sind Affiliate-Links: Buchen Sie darüber, erhalten wir eine Provision — für Sie ohne Aufpreis. Preise und Öffnungszeiten ändern sich; prüfen Sie vor der Reise immer die offizielle Seite.",
        "guides_h1": "Alle Reykjavík-Guides",
        "guides_title": "Alle Reykjavík-Guides | TouringBee",
        "guides_meta": "Alle Guides auf reykjavikwalk.com: Golden Circle, Blue Lagoon, Nordlichter, Hallgrímskirkja, Flughafentransfer, Routen und mehr.",
        "guides_lead": 'Dreißig Guides zu Reykjavík und den Ausflügen von dort, in Wellen veröffentlicht. Beginnen Sie mit dem <a href="/de/">kompletten Reykjavík-Guide</a> — alles Weitere geht bei einem Punkt in die Tiefe.',
        "in_production": "In Arbeit",
        "waves": {"P0": "Erste Welle — gerade in Arbeit",
                  "P1": "Zweite Welle", "P2": "Dritte Welle"},
        "updated": "Zuletzt aktualisiert: 6. August 2026",
        "privacy_title": "Datenschutzerklärung",
        "privacy_meta": "Wie reykjavikwalk.com mit Daten, Cookies und Affiliate-Tracking umgeht.",
        "affiliate_title": "Affiliate-Hinweis",
        "affiliate_meta": "Welche Links auf reykjavikwalk.com Affiliate-Links sind, mit wem wir arbeiten und was das für unsere Empfehlungen bedeutet.",
        "nf_h1": "Diese Seite gibt es nicht",
        "nf_p": "Entweder ist sie noch nicht veröffentlicht, oder der Link stimmt nicht. Beides lässt sich beheben.",
        "nf_cta1": "Kompletter Reykjavík-Guide",
    },

    "home": {
        "city": "Reykjavík",
        "city_desc": "Die Hauptstadt Islands und die nördlichste Hauptstadt der Welt.",
        "title": "Reykjavík Sehenswürdigkeiten: Stadtrundgang und Ausflüge | TouringBee",
        "meta": "Reykjavík richtig planen: ein Stadtrundgang auf eigene Faust mit 27 Stationen und Offline-Audio, dazu Golden Circle, Blue Lagoon, Nordlichter und alles, was die nördlichste Hauptstadt der Welt am besten kann.",
        "hero_alt": "Die Skulptur Sun Voyager an der Uferpromenade von Reykjavík unter weitem isländischem Himmel",
        "chip": "27 Stationen · 2–2,5 Stunden · funktioniert offline",
        "h1": "Reykjavík zu Fuß, in Ihrem Tempo",
        "sub": "Die nördlichste Hauptstadt der Welt lässt sich an einem Nachmittag erlaufen — wenn Sie wissen, was Sie da eigentlich vor sich haben. Das ist der komplette Guide: der Rundgang selbst, die Ausflüge, die eine Buchung wert sind, und die Jahreszeiten, die alles verändern.",
        "cta_inside": "Was drin ist", "cta_preview": "Hörprobe",
        "cta_daytrips": "Ausflüge und Touren",
        "intro1": "Reykjavík ist klein. Rund 140.000 Einwohner, ein Altstadtkern, den Sie in zwanzig Minuten durchqueren, und fast alles, wofür Sie gekommen sind, liegt an dieser einen Strecke. Der Rest ist eine kurze Busfahrt entfernt.",
        "intro2": "Genau das ist die Falle. Die Stadt wirkt wie eine, die man an einem Vormittag abhaken kann. Also fotografiert man die Kirche, fotografiert den Sun Voyager und fährt wieder ab. Ohne je gehört zu haben, wie ein Volk von Fischern die Royal Navy besiegte. Oder warum hier 2013 eine fertig geplante Straße verlegt wurde: Die Anwohner hatten sich für die Elfen eingesetzt.",
        "intro3": 'Es geht um die Geschichten. Deshalb gibt es den <a href="#audio">Reykjavík City Walking Tour</a>: 27 Stationen, von der Statue des Stadtgründers bis zu einem grasbewachsenen Hügel am Hafen, mit Fischtrockenhütte obendrauf. Sie drücken Play, Sie gehen, Sie halten an, wo Sie wollen. Zweieinhalb Stunden. Oder ein ganzer Nachmittag, wenn Sie unterwegs ständig auf einen Kaffee anhalten. Und das werden Sie.',
        "preview_h": "Hören Sie den Anfang",
        "preview_p": "30 Sekunden aus der Einleitung, auf Englisch",
        "highlights": [("Die Route", "Von Arnarhóll bis Þúfa, 27 nummerierte Stationen"),
                       ("Läuft auf", "iPhone und Android, vollständig offline"),
                       ("Das Tempo", "Ihres — Pause, Umweg, weiter"),
                       ("Zugriff", "Einmal zahlen, ein Jahr nutzen")],
        "prod_h2": "Der Reykjavík City Walking Tour",
        "prod_lead": "Geschrieben von Journalisten und Historikern, erzählt von Y'Own — einem Fischer aus Reykjavík, der noch Zeit hat, bevor er wieder ausläuft.",
        "prod_alt": "Die TouringBee-App mit der Route durch Reykjavík, hochgehalten vor der Hallgrímskirkja",
        "ticks": ["<strong>27 Audiostationen</strong> — Hallgrímskirkja, Sun Voyager, Harpa, Punkmuseum, ICGV Óðinn, Þúfa und mehr",
                  "<strong>Offline-GPS-Karte</strong> zeigt Ihren Standort — die Aufnahme starten Sie selbst, sobald Sie da sind",
                  "<strong>Illustrationen</strong>, damit Sie wissen, welches Gebäude Sie gerade ansehen",
                  "<strong>Sofortige Lieferung</strong> — die Aktivierungsmail kommt in wenigen Minuten",
                  "<strong>Keine Gruppe, kein Zeitplan</strong> — starten Sie an jedem Tag, zu jeder Stunde"],
        "why_h2": "Warum Reykjavík mehr verdient als einen Zwischenstopp",
        "why_p1": "Vor tausend Jahren warf ein Norweger namens Ingólfur Arnarson seine heiligen Hochsitzpfeiler über Bord und ließ die Götter entscheiden, wo er leben würde. Seine Sklaven brauchten drei Jahre, um sie zu finden — angespült in einer Bucht voller Dampf. Er nannte sie <em>Reykjavík</em>, Rauchbucht. Dieser Dampf ist bis heute der Grund, warum das Wasser in Ihrer Dusche hier nach Schwefel riecht.",
        "why_p2": "Die nächsten tausend Jahre wurde Island von anderen regiert. Erst Norwegen, dann Dänemark, dann ein Handelsmonopol aus Kopenhagen, das die Wirtschaft zwei Jahrhunderte lang abschnürte. Die Unabhängigkeit kam in Etappen und war erst 1944 vollständig. Das liegt innerhalb eines Menschenlebens, nicht in ferner Vergangenheit — und man merkt es: Dieses Land wundert sich noch immer ein wenig darüber, sich selbst zu regieren.",
        "why_img1_alt": "Das Regierungsgebäude in Reykjavík mit einer Statue davor",
        "why_img2_alt": "Eine Besucherin geht im Winter an der Skulptur Sun Voyager an der Sæbraut vorbei",
        "light_h3": "Alles hängt am Licht",
        "light_p1": "Nichts prägt einen Reykjavík-Besuch so stark wie der Himmel. Zwischen Mai und Juli geht die Sonne kaum unter, und die Stadt bleibt mit ihr wach. Im November und Dezember bleiben Ihnen vier bis fünf nutzbare Stunden Tageslicht — und alles Geplante muss da hineinpassen.",
        "light_p2": "Dafür gibt es die Nordlichter. Etwa von September bis April, in einer dunklen klaren Nacht, sehen Sie sie sogar aus der Stadt heraus. Die üblichen Plätze: der Leuchtturm Grótta und die Uferpromenade Sæbraut. Weder die Saison noch eine Tour garantiert etwas. Ein klarer Himmel schon.",
        "light_link": ("beste-reisezeit-reykjavik", "Wann Sie kommen sollten"),
        "free_h3": "Fast alles ist kostenlos",
        "free_p": "Der Rundgang selbst kostet nichts. Reykjavíks Zentrum ist ein öffentliches Museum: die Wandbilder, der Hafen, der Teich, das Parlament, die Regenbogenstraße. Bezahlen müssen Sie nur für weniges: den Aufzug im Turm der Hallgrímskirkja, Perlan, die Museen und die Thermalbäder — ein paar hundert Kronen, die sich lohnen. Heben Sie sich das Budget lieber für die Ausflüge auf. Da wird Island teuer.",
        "free_link": ("reykjavik-preise", "Was Reykjavík wirklich kostet"),
        "weird_h3": "Eine Stadt, die zu ihren Schrullen steht",
        "weird_p1": "Reykjavík hat ein Penismuseum, ein Punkmuseum in einer früheren öffentlichen Toilette, ein Wandbild mit Vampir und eine Dampflok, für die es nie eine Eisenbahnstrecke gab. Siebzehn Jahre lang pausierte im Juli das Fernsehen, damit die Leute vor die Tür gingen. Und einmal stürzte die Stadt eine Regierung — mit Töpfen und Pfannen.",
        "weird_p2": "Auf den Postkarten steht nichts davon. Auf der Route liegt alles.",
        "weird_img_alt": "Die erhaltene Dampflokomotive am alten Hafen von Reykjavík",
        "oneday_link": ("ein-tag-in-reykjavik", "Zum Tagesplan"),
        "tiles_h2": "Was Sie unterwegs sehen",
        "tiles_lead": "Sechs von siebenundzwanzig Stationen. Den Rest treffen Sie unterwegs.",
        "tiles": [
            {"href": "hallgrimskirkja", "img": "tile-hallgrimskirkja", "h": "Hallgrímskirkja",
             "alt": "Die Hallgrímskirkja von unten, mit wehender isländischer Flagge",
             "p": "Die Kirche aus Basaltsäulen — und vom Turm der beste Blick über die Stadt"},
            {"href": "regenbogenstrasse-laugavegur", "img": "tile-rainbow-street", "h": "Regenbogenstraße",
             "alt": "Skólavörðustígur, die in Regenbogenfarben bemalte Straße hinauf zur Hallgrímskirkja",
             "p": "Skólavörðustígur — für die Pride bemalt und nie wieder abgewaschen"},
            {"href": "harpa", "img": "tile-harpa", "h": "Harpa",
             "alt": "Die gläserne Wabenfassade des Konzerthauses Harpa in der Dämmerung",
             "p": "Eine Wabe aus Glas, gebaut mitten durch einen Crash, der sie fast erledigt hätte"},
            {"href": "alter-hafen-reykjavik", "img": "tile-old-harbour", "h": "Der alte Hafen",
             "alt": "Fischerboote im alten Hafen von Reykjavík",
             "p": "Von hier fahren die Walboote — und hier wurden die Kabeljaukriege gewonnen"},
            {"href": "reykjavik-sehenswuerdigkeiten", "img": "tile-whales", "h": "Whales of Iceland",
             "alt": "Lebensgroße Walmodelle in blauem Licht in der Ausstellung Whales of Iceland",
             "p": "Dreiundzwanzig lebensgroße Wale in einer dunklen Halle am Wasser"},
            {"href": "reykjavik-sehenswuerdigkeiten", "img": "tile-thufa", "h": "Þúfa",
             "alt": "Þúfa, der grasbewachsene Spiralhügel mit der Fischtrockenhütte obendrauf",
             "p": "Das Ende der Route: ein Spiralhügel mit einer Fischtrockenhütte auf der Kuppe"}],
        "how_h2": "So funktioniert der Audioguide",
        "steps": [{"h": "Kaufen", "p": "Eine Zahlung auf dieser Seite. Die Aktivierungsmail kommt in wenigen Minuten."},
                  {"h": "Laden", "p": "Kostenlose TouringBee-App installieren, aktivieren und die Tour über das Hotel-WLAN herunterladen."},
                  {"h": "Gehen", "p": "Die Offline-Karte zeigt Ihren Standort. An einer Station drücken Sie Play — die App redet nie von selbst dazwischen."},
                  {"h": "Behalten", "p": "Ein Jahr Zugriff. Kommen Sie im Winter wieder und gehen Sie dieselbe Route im Dunkeln."}],
        "how_note": "Nehmen Sie Kopfhörer mit. Der isländische Wind ist lauter als Ihr Handylautsprecher.",
        "basics_h2": "Reykjavík: das Praktische",
        "facts": [("Anreise", "Keflavík (KEF), ca. 45 Min. mit Flybus oder Auto"),
                  ("Währung", "Isländische Krone (ISK) — Karte überall, Bargeld fast nie"),
                  ("Vor Ort", "Zentrum zu Fuß, Strætó-Busse, Mietwagen für Ausflüge"),
                  ("Sprache", "Isländisch; Englisch wird praktisch überall gesprochen"),
                  ("Nordlichtsaison", "ca. September bis April, nur in dunklen klaren Nächten"),
                  ("Mitternachtssonne", "ca. Mai bis Juli, kaum echte Dunkelheit"),
                  ("Wetter", "Wechselt stündlich. Wasserdichte Schichten schlagen den Regenschirm"),
                  ("Leitungswasser", "Ausgezeichnet und gratis. Kaufen Sie hier nie Flaschenwasser")],
        "book_h3": "Buchen Sie die kostenpflichtigen Ziele vorab",
        "book_p": "Reykjavík selbst ist selten ausgebucht — das, wofür Leute einfliegen, schon: Blue Lagoon, Sky Lagoon, Nordlichtboote und im Sommer der Golden Circle. Wer vorab bucht, muss den Rundgang außerdem nicht um eine Warteschlange herum planen.",
        "book_cta": "Reykjavík-Tickets bei Tiqets",
        "partners_h2": "Ausflüge und Tickets",
        "partners_lead": "Der Rundgang deckt die Stadt ab. Alles Weitere liegt außerhalb — und das sind die Buchungen, die Sie vor der Landung erledigen sollten.",
        "p_golden_h": "Golden Circle",
        "p_golden_p": "Drei Ziele, ein langer Tag: die klassische Islandrunde — und die meistbesuchte.",
        "p_blue_p": "Nah am Flughafen, also ideal als erster oder letzter Stopp. Zeitfenster sind schnell weg.",
        "p_blue_alt": "Die Thermallagune Blue Lagoon, Dampf über milchig blauem Wasser",
        "p_aurora_h": "Nordlichter",
        "p_aurora_p": "Boote und Kleinbusse, die dem klaren Himmel hinterherfahren. Die meisten buchen kostenlos um, wenn es zuzieht.",
        "p_aurora_alt": "Grüne Nordlichter über einer Straße außerhalb von Reykjavík",
        "p_sky_p": "Die stadtnahe Alternative zur Blue Lagoon: näher, günstiger zu erreichen, gleicher Dampf.",
        "p_sky_alt": "Eine abends blau beleuchtete Thermallagune bei Reykjavík",
        "car_h3": "Selbst fahren? Buchen Sie früh",
        "car_p": "Den Golden Circle und die Südküste fahren Sie besser selbst: Sie halten, wo Sie wollen, und sind an keinen Busfahrplan gebunden. Islands Mietwagenflotte ist klein, im Sommer ist sie Wochen im Voraus vergeben. Das ist eine der wenigen Buchungen, die wirklich vor dem Abflug gehören.",
        "car_cta": "Mietwagen vergleichen",
        "car_link": ("golden-circle-mietwagen-oder-tour", "Mietwagen oder Tour?"),
        "cross_h2": "Weitere Audio-Rundgänge von TouringBee",
        "cross_lead": "Island handelte zwei Jahrhunderte lang mit Kopenhagen — unfreiwillig. Die Tour erzählt diese Geschichte; hören Sie ruhig auch die andere Seite.",
        "cross": [{"h": "Kopenhagen", "path": "product/copenhagen-city-tour",
                   "p": "Die Stadt, die zweihundert Jahre lang Islands Wirtschaft führte — zu Fuß in etwa drei Stunden.",
                   "cta": "Copenhagen Walking Tour"},
                  {"h": "Oslo", "path": "product/oslo-city-tour",
                   "p": "Von dort kam Ingólfur Arnarson, mehr oder weniger — und dort beginnen die Sagas.",
                   "cta": "Oslo City Walking Tour"},
                  {"h": "Alle Touren", "path": "shop-tbee",
                   "p": "Rund hundert Audio-Rundgänge auf eigene Faust, in Europa und darüber hinaus.",
                   "cta": "Zum Shop"}],
        "plan_h2": "Ihren Besuch planen",
        "plan": [{"h": "Anreise", "links": [("flughafen-keflavik-reykjavik", "Flughafen Keflavík"), ("fortbewegung-reykjavik", "Vor Ort unterwegs")]},
                 {"h": "Ausflüge", "links": [("golden-circle", "Golden Circle"), ("suedkueste-island", "Südküste"), ("tagesausfluege-ab-reykjavik", "Alle Ausflüge")]},
                 {"h": "Zeitpunkt", "links": [("beste-reisezeit-reykjavik", "Beste Reisezeit"), ("packliste-island", "Packliste"), ("nordlichter-reykjavik", "Nordlichter")]},
                 {"h": "In der Stadt", "links": [("hallgrimskirkja", "Hallgrímskirkja"), ("perlan", "Perlan"), ("street-art-reykjavik", "Street Art")]},
                 {"h": "Wasser", "links": [("blue-lagoon", "Blue Lagoon"), ("sky-lagoon", "Sky Lagoon"), ("thermalbaeder-reykjavik", "Stadtbäder")]},
                 {"h": "Praktisch", "links": [("reykjavik-preise", "Was es kostet"), ("unterkunft-reykjavik", "Wo wohnen"), ("islaendische-kueche", "Was essen")]}],
        "faq_h2": "Häufige Fragen",
        "faq": [
            ("Wie viele Tage braucht man für Reykjavík?", "Zwei volle Tage decken die Stadt bequem ab: einer für den Rundgang und die Museen, einer für eine Lagune oder den Hafen. Rechnen Sie pro großem Ausflug einen weiteren Tag — einen für den Golden Circle, einen für die Südküste. Die meisten unterschätzen, wie viel Zeit einer Islandreise im Fahrzeug vergeht."),
            ("Lässt sich das Zentrum zu Fuß erkunden?", "Vollständig. Die 27 Stationen ergeben rund 5 km, praktisch ohne Steigung — abgesehen vom Anstieg über den Skólavörðustígur zur Kirche. Die Grenze setzt das Wetter, nicht die Distanz."),
            ("Startet der Audioguide beim Gehen automatisch?", "Nein, und das ist Absicht. Die Offline-Karte zeigt Ihren Standort, aber Play drücken Sie selbst, wenn Sie an der Station stehen. Die GPS-Genauigkeit von Handys schwankt zu stark für verlässliche automatische Auslöser. Manuell heißt: Sie verpassen keine Geschichte, nur weil Ihr Telefon Sie eine Straße weiter vermutet hat."),
            ("Brauche ich unterwegs mobiles Internet?", "Nein. Laden Sie die Tour einmal über WLAN herunter — danach läuft alles offline, Karte inklusive."),
            ("Kann man die Nordlichter aus Reykjavík heraus sehen?", "Ja, in einer dunklen klaren Nacht etwa zwischen September und April. Üblich sind der Leuchtturm Grótta auf Seltjarnarnes und der dunkle Abschnitt der Uferpromenade Sæbraut. Die Lichter der Innenstadt arbeiten gegen Sie, und Wolken schlagen alles — keine Saison und keine Tour kann Nordlichter versprechen."),
            ("Ist Reykjavík teuer?", "Essen gehen und Alkohol: ja, deutlich. Die Stadt selbst nicht — Rundgang, Hafen, Wandbilder und Parks kosten nichts, das Leitungswasser ist ausgezeichnet, und die Thermalbäder kosten einen Bruchteil der Blue Lagoon. Das Budget geht für Ausflüge und Abendessen drauf."),
            ("Was soll ich anziehen?", "Regenjacke, warme Zwischenschicht, rutschfeste Schuhe und eine Mütze — in jedem Monat. Ein Regenschirm nützt nichts: Der Wind in Reykjavík zerlegt ihn, und die Einheimischen sehen es."),
            ("Gibt es den Audioguide auf Deutsch?", "Der Reykjavík City Walking Tour wird derzeit auf Englisch erzählt. Andere TouringBee-Touren gibt es in acht Sprachen."),
        ],
        "final_h2": "Gehen Sie los — und hören Sie, warum",
        "final_p": "Siebenundzwanzig Stationen, zweieinhalb Stunden — und ein Fischer namens Y'Own, der Ihnen erklärt, warum nichts davon das ist, wonach es aussieht.",
        "final_cta2": "Ausflüge ansehen",
    },

    "legal": {
        "privacy": '''<h2>Wer diese Seite betreibt</h2>
<p>reykjavikwalk.com wird herausgegeben von Touringbee Limited, eingetragen in der Republik Irland unter der Nummer 660321. Kontakt: <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>
<h2>Was wir erheben</h2>
<p>Sie brauchen kein Konto, und wir erheben auf dieser Seite weder Namen noch Adressen noch Zahlungsdaten. Beim Kauf des Audioguides läuft die Kasse über Bókun, die Zahlung über Stripe — Ihre Kartendaten liegen bei ihnen, nie bei uns.</p>
<p>Wie fast jede Website protokolliert unser Hoster Standard-Serverlogs: IP-Adresse, Browsertyp, angefragte Seite und Zeitpunkt. Sie dienen dem Betrieb und der Sicherheit.</p>
<h2>Analyse und Cookies</h2>
<p>Wir nutzen datenschutzfreundliche Analyse, um Seitenaufrufe zu zählen und zu erkennen, welche Guides nützlich sind. Wir verkaufen keine Daten und schalten keine Werbenetzwerke.</p>
<p>Folgen Sie einem Affiliate-Link zu Partnern wie GetYourGuide, Tiqets oder Booking.com, kann dieser Partner ein Cookie setzen, um uns eine Buchung zuzuordnen. Ab dann gilt dessen Cookie-Richtlinie.</p>
<h2>Der Audioguide</h2>
<p>Käufe des Reykjavík City Walking Tour wickeln Bókun (Kasse) und TouringBee (Versand des Aktivierungslinks) ab. Deren Bedingungen: <a href="https://touringbee.com/terms-and-conditions-of-use/" target="_blank" rel="noopener">touringbee.com/terms-and-conditions-of-use</a>.</p>
<h2>Ihre Rechte</h2>
<p>In der EU und im Vereinigten Königreich können Sie Auskunft über Ihre gespeicherten personenbezogenen Daten verlangen sowie deren Berichtigung oder Löschung. Schreiben Sie an <a href="mailto:info@touringbee.com">info@touringbee.com</a> — wir antworten innerhalb von 30 Tagen.</p>''',
        "affiliate": '''<p>Einige Links auf reykjavikwalk.com sind Affiliate-Links. Buchen oder kaufen Sie darüber, erhalten wir eine Provision. Für Sie ändert sich nichts — der Preis ist derselbe wie direkt.</p>
<h2>Mit wem wir arbeiten</h2>
<ul class="ticks">
<li><strong>GetYourGuide</strong> — Ausflüge, Nordlichttouren, Walbeobachtung, Transfers</li>
<li><strong>Tiqets</strong> — Tickets für Attraktionen und Lagunen</li>
<li><strong>Booking.com</strong> — Hotels und Mietwagen</li>
</ul>
<h2>Unser eigenes Produkt</h2>
<p>Den Audioguide Reykjavík City Walking Tour produziert TouringBee, der Herausgeber dieser Seite. Wir sind da nicht neutral: Wir halten ihn für die beste Art, Reykjavík zu erlaufen, und sagen das auch. Sie können ihn hier oder direkt bei TouringBee kaufen — zum selben Preis.</p>
<h2>Was das für unsere Empfehlungen bedeutet</h2>
<p>Provision entscheidet nie über den Inhalt eines Guides. Wir empfehlen mehrfach die städtischen Thermalbäder statt der Blue Lagoon, obwohl die Blue Lagoon besser zahlt, und wir schreiben, welche Attraktionen ihr Geld nicht wert sind. Eine Empfehlung, die es nur gibt, weil sie zahlt, ist keine.</p>
<p>Preise, Öffnungszeiten und Verfügbarkeit ändern sich. Prüfen Sie vor der Reise immer die Seite des Anbieters.</p>
<p>Fragen: <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>''',
    },
}
