# -*- coding: utf-8 -*-
"""English — source master."""

G = [
    ("P0", "golden-circle", "Golden Circle from Reykjavik", "Þingvellir, Geysir and Gullfoss in one day — self-drive or guided."),
    ("P0", "blue-lagoon", "Blue Lagoon: tickets &amp; transfers", "How to fit it around your flights, and whether it's worth the price."),
    ("P0", "northern-lights-reykjavik", "Northern Lights in &amp; near Reykjavik", "Season, forecast, city spots and when a tour actually helps."),
    ("P0", "hallgrimskirkja", "Hallgrímskirkja &amp; the tower view", "The church, the lift, the queue, and the best time of day to go up."),
    ("P0", "keflavik-airport-to-reykjavik", "Keflavík airport to the city", "Flybus, private transfer, rental car — cost and time compared."),
    ("P0", "sky-lagoon", "Sky Lagoon", "The in-city geothermal spa and its seven-step ritual."),
    ("P0", "whale-watching-reykjavik", "Whale watching &amp; puffins", "Boats from the Old Harbour, seasons and seasickness."),
    ("P0", "best-time-to-visit-reykjavik", "Best time to visit Reykjavik", "Daylight, aurora, weather and prices, month by month."),
    ("P0", "one-day-in-reykjavik", "One day in Reykjavik", "The walking itinerary that fits everything essential into a day."),
    ("P0", "things-to-do-in-reykjavik", "Best things to do in Reykjavik", "The full list, ranked by whether it's worth your limited daylight."),
    ("P1", "golden-circle-self-drive-vs-tour", "Golden Circle: self-drive or tour?", "Honest cost and time comparison for both."),
    ("P1", "day-trips-from-reykjavik", "Day trips from Reykjavik", "Every trip worth doing from the city, with driving times."),
    ("P1", "south-coast-day-trip", "South Coast day trip", "Seljalandsfoss, Skógafoss and Reynisfjara black beach."),
    ("P1", "sun-voyager", "Sun Voyager &amp; the waterfront", "The sculpture everyone photographs, and what it actually is."),
    ("P1", "harpa-concert-hall", "Harpa Concert Hall", "The glass honeycomb, and how it survived the crash."),
    ("P1", "old-harbour-reykjavik", "The Old Harbour", "Boats, food, the coastguard ship, and the Cod Wars."),
    ("P1", "rainbow-street-laugavegur", "Rainbow Street &amp; Laugavegur", "The painted street and the main shopping strip."),
    ("P1", "perlan", "Perlan", "The dome, the ice cave and the observation deck."),
    ("P1", "two-days-in-reykjavik", "Two days in Reykjavik", "A slower plan with room for a lagoon."),
    ("P1", "what-to-wear-in-iceland", "What to wear &amp; pack", "Layers that work in weather that changes hourly."),
    ("P1", "getting-around-reykjavik", "Getting around Reykjavik", "On foot, by Strætó bus, and when you need a car."),
    ("P1", "is-reykjavik-expensive", "Is Reykjavik expensive?", "What things actually cost, and where to save."),
    ("P1", "where-to-stay-in-reykjavik", "Where to stay in Reykjavik", "Neighbourhoods explained, and what you pay for each."),
    ("P2", "reykjavik-street-art", "Reykjavik street art walk", "The murals, including the vampire nobody explains."),
    ("P2", "grotta-lighthouse", "Grótta &amp; the best aurora spots", "Where to stand when the sky goes green."),
    ("P2", "tjornin-austurvollur-parliament", "Tjörnin, Austurvöllur &amp; the Alþingi", "The pond, the square and the world's oldest parliament."),
    ("P2", "reykjavik-food-guide", "Icelandic food guide", "Pylsa, skyr, lamb soup, hákarl — what to try and what to skip."),
    ("P2", "geothermal-pools-reykjavik", "Geothermal pools &amp; pool etiquette", "The shower rules nobody warns tourists about."),
    ("P2", "free-things-to-do-in-reykjavik", "Free things to do in Reykjavik", "A full day that costs nothing."),
    ("P2", "reykjavik-museums", "Reykjavik museums", "The National Museum, Settlement Exhibition 871±2 and the strange ones."),
]

CONTENT = {
    "slugs": {"guides": "guides", "privacy": "privacy-policy",
              "affiliate": "affiliate-disclosure"},
    "guides": [{"wave": w, "slug": s, "title": t, "desc": d} for w, s, t, d in G],

    "ui": {
        "menu": "Guides", "menu_all": "All guides",
        "buy": "Buy the audio guide — €9.99",
        "see_tours": "See tours", "check_tickets": "Check tickets",
        "sticky_title": "Reykjavík City Walking Tour — €9.99",
        "sticky_sub": "4.7 ★ · 27 stops · offline · in English",
        "sticky_btn": "Buy now",
        "rating_aria": "Rated 4.7 out of 5",
        "rating_label": "average traveller rating",
        "price_display": "€9.99",
        "price_sub": "One payment · no subscription · 1-year access",
        "checkout_note": "Secure checkout on this page. Prefer the shop?",
        "open_shop": "Open it on TouringBee",
        "audio_fallback": "Your browser does not support audio playback.",
        "product_name": "Reykjavík City Walking Tour",
        "product_name_full": "Reykjavík City Walking Tour — self-guided audio guide",
        "product_desc": "A 27-stop self-guided walking tour of Reykjavík with offline audio and an offline GPS map, from the Ingólfur Arnarson monument to Þúfa. About 2–2.5 hours.",
        "product_category": "Self-guided audio tour",
        "author_h": "About the author",
        "author_alt": "Eugene, author of the TouringBee audio tours",
        "author_bio": "Eugene has spent sixteen years living in France, worked as a guide, and founded the travel content network paris10.travel. He has visited more than 300 French towns and villages and writes the TouringBee audio tours. He builds these guides the way he'd brief a friend before a trip: what's actually worth your time, what to book, and what to skip.",
        "author_bio_plain": "Former guide, founder of paris10.travel, author of TouringBee audio tours.",
        "f_explore": "Explore", "f_product": "The audio guide", "f_legal": "Legal",
        "f_langs": "Languages", "f_alltours": "All TouringBee tours",
        "f_terms": "Terms &amp; conditions",
        "langnames": {"en": "English", "fr": "Français", "de": "Deutsch", "es": "Español",
                      "it": "Italiano", "pt": "Português", "pl": "Polski", "ru": "Русский"},
        "disclaimer": 'reykjavikwalk.com is published by Touringbee Limited (Ireland, company no. 660321). Some links on this site are affiliate links — if you book through them we may earn a commission at no extra cost to you. Prices and opening hours change; always confirm on the official site before you travel.',
        "guides_h1": "All Reykjavik guides",
        "guides_title": "All Reykjavik Guides | TouringBee",
        "guides_meta": "Every guide on reykjavikwalk.com: the Golden Circle, Blue Lagoon, Northern Lights, Hallgrímskirkja, airport transfers, itineraries and more.",
        "guides_lead": 'Thirty guides to Reykjavík and the trips people take from it, published in waves. Start with the <a href="/">complete guide to Reykjavik</a> — everything below goes deeper on one piece of it.',
        "in_production": "In production",
        "waves": {"P0": "First wave — in production now",
                  "P1": "Second wave", "P2": "Third wave"},
        "updated": "Last updated: 6 August 2026",
        "privacy_title": "Privacy policy",
        "privacy_meta": "How reykjavikwalk.com handles data, cookies and affiliate tracking.",
        "affiliate_title": "Affiliate disclosure",
        "affiliate_meta": "Which links on reykjavikwalk.com are affiliate links, who we work with, and how it affects our recommendations.",
        "nf_h1": "This page isn't here",
        "nf_p": "Either it hasn't been published yet, or the link is wrong. Both are fixable.",
        "nf_cta1": "Reykjavik complete guide",
    },

    "home": {
        "city": "Reykjavík",
        "city_desc": "The capital of Iceland and the world's northernmost capital city.",
        "title": "Reykjavik Guide: Self-Guided Walking Tour &amp; Day Trips | TouringBee",
        "meta": "Plan Reykjavik properly: a 27-stop self-guided walking tour with offline audio, plus the Golden Circle, Blue Lagoon, Northern Lights and everything the world's northernmost capital does best.",
        "hero_alt": "The Sun Voyager sculpture on the Reykjavik waterfront under a wide Icelandic sky",
        "chip": "27 stops · 2–2.5 hours · works offline",
        "h1": "Reykjavik, on foot and in your own time",
        "sub": "The world's northernmost capital fits in an afternoon of walking — if you know what you're looking at. This is the complete guide to Reykjavik: the walk itself, the day trips worth booking, and the seasons that change everything.",
        "cta_inside": "See what's inside", "cta_preview": "Listen to a preview",
        "cta_daytrips": "Day trips &amp; tours",
        "intro1": "Reykjavik is small. Roughly 140,000 people live here, the old centre is about twenty minutes end to end, and almost everything you came for sits on that one walk. The rest is a bus ride away.",
        "intro2": 'That size is the trap. It looks like a city you can "do" in a morning. So people photograph the church, photograph the Sun Voyager, and leave. Never having heard how a nation of fishermen beat the Royal Navy. Or why, in 2013, a finished road plan was shifted aside — the neighbours had objected on behalf of the elves.',
        "intro3": 'The stories are the point. That\'s why we made the <a href="#audio">Reykjavík City Walking Tour</a> — 27 stops, from the statue of the man who founded the place to a grass-covered mound by the harbour with a fish-drying shed on top. You press play, you walk, you stop where you like. About two and a half hours. Or a whole afternoon, if you keep stopping for coffee. Which you will.',
        "preview_h": "Listen to the opening",
        "preview_p": "30 seconds from the introduction, in English",
        "highlights": [("The walk", "Arnarhóll to Þúfa, 27 numbered stops"),
                       ("Runs on", "iPhone &amp; Android, fully offline"),
                       ("Pace", "Yours — pause, detour, resume"),
                       ("Access", "One payment, one year")],
        "prod_h2": "The Reykjavík City Walking Tour",
        "prod_lead": "Written by journalists and historians, narrated in the voice of Y'Own — a Reykjavik fisherman with time to kill before his next trip out to sea.",
        "prod_alt": "The TouringBee app showing the Reykjavik walking route, held up in front of Hallgrímskirkja",
        "ticks": ["<strong>27 audio stops</strong> — Hallgrímskirkja, the Sun Voyager, Harpa, the Punk Museum, ICGV Óðinn, Þúfa and more",
                  "<strong>Offline GPS map</strong> shows where you are — you start each recording yourself when you reach the spot",
                  "<strong>Illustrations</strong> so you know which building you're looking at",
                  "<strong>Instant delivery</strong> — activation email arrives in a few minutes",
                  "<strong>No group, no schedule</strong> — start any day, any hour"],
        "why_h2": "Why Reykjavik is worth more than a stopover",
        "why_p1": "A thousand years ago a Norwegian named Ingólfur Arnarson threw his sacred high-seat pillars overboard and let the gods choose where he'd live. It took his slaves three years to find them, washed up in a bay full of steam. He called it <em>Reykjavík</em> — smoky bay — and the steam is still the reason the water in your shower here smells of sulphur.",
        "why_p2": "Iceland spent the next thousand years being governed by other people. Norway, then Denmark, then a trade monopoly out of Copenhagen that strangled the economy for two centuries. Independence came in stages and only finished in 1944. That's within living memory, and you can feel it — this is a country that is still slightly amazed to be running itself.",
        "why_img1_alt": "Government House in Reykjavik with a statue in front of it",
        "why_img2_alt": "A visitor walking past the Sun Voyager sculpture on the Sæbraut waterfront in winter",
        "light_h3": "The light is the whole trip",
        "light_p1": "Nothing else shapes a Reykjavik visit as much as the sky. Between May and July the sun barely bothers setting and the city stays awake with it. In November and December you get four or five usable hours of daylight, and everything you planned has to fit inside them.",
        "light_p2": "The trade is aurora. Roughly September to April, on a dark clear night, you can see the Northern Lights from inside the city — Grótta lighthouse and the Sæbraut waterfront are the usual spots. Neither the season nor a tour guarantees anything. Clear sky does.",
        "light_link": ("best-time-to-visit-reykjavik", "When to come"),
        "free_h3": "Almost all of this is free",
        "free_p": "The walk itself costs nothing. Reykjavik's centre is a public museum — the murals, the harbour, the pond, the parliament, the rainbow street. The paid bits are few: the lift up the Hallgrímskirkja tower, Perlan, the museums, and the geothermal pools — a few hundred krónur, and worth it. Budget for the day trips instead. That's where Iceland gets expensive.",
        "free_link": ("is-reykjavik-expensive", "What Reykjavik actually costs"),
        "weird_h3": "A city that keeps its weird",
        "weird_p1": "Reykjavik has a museum of phalluses, a punk museum in a former public toilet, a mural of a vampire, and a steam locomotive that never had a railway to run on. It banned television in July for seventeen years so people would go outside. It once brought down a government with pots and pans.",
        "weird_p2": "None of this is on the postcards, and all of it is on the walk.",
        "weird_img_alt": "The preserved steam locomotive by Reykjavik's old harbour",
        "oneday_link": ("one-day-in-reykjavik", "See the one-day plan"),
        "tiles_h2": "What you'll see on the walk",
        "tiles_lead": "Six of the twenty-seven stops. The rest you'll meet on the way.",
        "tiles": [
            {"href": "hallgrimskirkja", "img": "tile-hallgrimskirkja", "h": "Hallgrímskirkja",
             "alt": "Hallgrímskirkja church seen from below with the Icelandic flag flying",
             "p": "The basalt-column church, and the best view in the city from its tower"},
            {"href": "rainbow-street-laugavegur", "img": "tile-rainbow-street", "h": "Rainbow Street",
             "alt": "Skólavörðustígur, the rainbow-painted street leading up to Hallgrímskirkja",
             "p": "Skólavörðustígur, painted for Pride and never washed off"},
            {"href": "harpa-concert-hall", "img": "tile-harpa", "h": "Harpa",
             "alt": "The glass honeycomb façade of Harpa Concert Hall at dusk",
             "p": "A glass honeycomb built through a financial crash that nearly killed it"},
            {"href": "old-harbour-reykjavik", "img": "tile-old-harbour", "h": "The Old Harbour",
             "alt": "Fishing boats moored at Reykjavik's old harbour",
             "p": "Where the whale boats leave — and where the Cod Wars were won"},
            {"href": "things-to-do-in-reykjavik", "img": "tile-whales", "h": "Whales of Iceland",
             "alt": "Life-size whale models lit in blue inside the Whales of Iceland exhibition",
             "p": "Twenty-three life-size whales in a dark hangar by the water"},
            {"href": "things-to-do-in-reykjavik", "img": "tile-thufa", "h": "Þúfa",
             "alt": "Þúfa, the grass-covered spiral mound with a fish-drying hut on top",
             "p": "The end of the walk: a spiral hill with a fish-drying shed on top"}],
        "how_h2": "How the audio tour works",
        "steps": [{"h": "Buy", "p": "One payment on this page. The activation email lands within a few minutes."},
                  {"h": "Download", "p": "Install the free TouringBee app, activate, and download the tour over hotel Wi-Fi."},
                  {"h": "Walk", "p": "The offline map shows where you are. When you reach a stop, you press play — the app never interrupts you on its own."},
                  {"h": "Keep it", "p": "A year of access. Come back in winter and walk the same route in the dark."}],
        "how_note": "Bring headphones. Icelandic wind is louder than your phone speaker.",
        "basics_h2": "Visiting Reykjavik: the basics",
        "facts": [("Getting in", "Keflavík (KEF), ~45 min by Flybus or car"),
                  ("Currency", "Icelandic króna (ISK) — cards everywhere, cash almost never"),
                  ("Getting around", "On foot in the centre; Strætó buses; rental car for day trips"),
                  ("Language", "Icelandic; English is spoken essentially everywhere"),
                  ("Aurora season", "~September to April, dark clear nights only"),
                  ("Midnight sun", "~May to July, barely any true darkness"),
                  ("Weather", "Changes hourly. Waterproof layers beat an umbrella"),
                  ("Tap water", "Excellent and free. Never buy bottled here")],
        "book_h3": "Book the paid attractions before you go",
        "book_p": "Reykjavik itself rarely sells out, but the things people fly in for do — the Blue Lagoon, Sky Lagoon, Northern Lights boats and the Golden Circle in summer. Pre-booking also saves the walk from being rearranged around a queue.",
        "book_cta": "Reykjavik tickets on Tiqets",
        "partners_h2": "Day trips &amp; tickets",
        "partners_lead": "The walk covers the city. Everything below happens outside it — and these are the bookings worth making before you land.",
        "p_golden_h": "Golden Circle",
        "p_golden_p": "Three sights, one long day — the classic Iceland loop, and the busiest.",
        "p_blue_p": "Near the airport, so it works as a first or last stop. Slots sell out — book ahead.",
        "p_blue_alt": "The Blue Lagoon geothermal spa with steam rising off milky blue water",
        "p_aurora_h": "Northern Lights",
        "p_aurora_p": "Boats and minibuses that chase the clear sky. Most rebook you free if it clouds over.",
        "p_aurora_alt": "Green Northern Lights over a road outside Reykjavik",
        "p_sky_p": "The city-side alternative to the Blue Lagoon — closer, cheaper to reach, same steam.",
        "p_sky_alt": "A geothermal lagoon lit blue in the evening near Reykjavik",
        "car_h3": "Driving yourself? Book the car early",
        "car_p": "The Golden Circle and the South Coast are both better self-driven — you stop where you want and skip the coach timetable. Iceland's rental fleet is small and summer sells out weeks ahead, so this is one of the few bookings genuinely worth making before you fly.",
        "car_cta": "Compare rental cars",
        "car_link": ("golden-circle-self-drive-vs-tour", "Self-drive vs guided tour"),
        "cross_h2": "More audio walks by TouringBee",
        "cross_lead": "Iceland traded with Copenhagen for two centuries — under duress. The tour tells that story; you may as well hear the other side of it.",
        "cross": [{"h": "Copenhagen", "path": "product/copenhagen-city-tour",
                   "p": "The city that ran Iceland's economy for two hundred years, walked in about three hours.",
                   "cta": "Copenhagen Walking Tour"},
                  {"h": "Oslo", "path": "product/oslo-city-tour",
                   "p": "Where Ingólfur Arnarson sailed from, more or less, and where the sagas start.",
                   "cta": "Oslo City Walking Tour"},
                  {"h": "All tours", "path": "shop-tbee",
                   "p": "Around a hundred self-guided audio walks across Europe and beyond.",
                   "cta": "Browse the shop"}],
        "plan_h2": "Plan your visit",
        "plan": [{"h": "Getting here", "links": [("keflavik-airport-to-reykjavik", "Keflavík airport to the city"), ("getting-around-reykjavik", "Getting around")]},
                 {"h": "Day trips", "links": [("golden-circle", "Golden Circle"), ("south-coast-day-trip", "South Coast"), ("day-trips-from-reykjavik", "All day trips")]},
                 {"h": "Timing it", "links": [("best-time-to-visit-reykjavik", "Best time to visit"), ("what-to-wear-in-iceland", "What to wear"), ("northern-lights-reykjavik", "Northern Lights")]},
                 {"h": "In the city", "links": [("hallgrimskirkja", "Hallgrímskirkja"), ("perlan", "Perlan"), ("reykjavik-street-art", "Street art walk")]},
                 {"h": "Water", "links": [("blue-lagoon", "Blue Lagoon"), ("sky-lagoon", "Sky Lagoon"), ("geothermal-pools-reykjavik", "City pools")]},
                 {"h": "Practical", "links": [("is-reykjavik-expensive", "What it costs"), ("where-to-stay-in-reykjavik", "Where to stay"), ("reykjavik-food-guide", "What to eat")]}],
        "faq_h2": "Common questions",
        "faq": [
            ("How many days do you need in Reykjavik?", "Two full days covers the city comfortably — one for the walk and the museums, one for a lagoon or the harbour. Add a day for every major trip out of town: one for the Golden Circle, one for the South Coast. Most people underestimate how much of an Iceland trip is spent in a vehicle."),
            ("Is the city centre walkable?", "Entirely. The whole 27-stop route runs about 5 km with almost no gradient except the climb up Skólavörðustígur to the church. The limiting factor is weather, not distance."),
            ("Does the audio guide play automatically as I walk?", "No, and that's deliberate. The offline map shows where you are, but you press play yourself when you arrive at a stop. Phone GPS accuracy varies too much for automatic triggers to be reliable — manual means you never miss a story because your phone thought you were on the next street."),
            ("Do I need mobile data during the walk?", "No. Download the tour once over Wi-Fi and it runs entirely offline, map included."),
            ("Can I see the Northern Lights from inside Reykjavik?", "Yes, on a dark clear night between roughly September and April. Grótta lighthouse on Seltjarnarnes and the dark stretch of the Sæbraut waterfront are the usual spots. Light pollution downtown works against you, and cloud beats everything — no season or tour can promise an aurora."),
            ("Is Reykjavik expensive?", "Eating out and alcohol are genuinely expensive. The city itself is not — the walk, the harbour, the murals and the parks are free, tap water is excellent, and the geothermal pools cost a fraction of the Blue Lagoon. The budget goes on day trips and dinner."),
            ("What should I wear?", "Waterproof jacket, warm mid-layer, non-slip shoes, and a hat any month of the year. An umbrella is useless — Reykjavik wind will destroy it, and locals will notice."),
            ("Is the audio guide available in my language?", "The Reykjavík City Walking Tour is currently narrated in English. Other TouringBee tours are available in eight languages."),
        ],
        "final_h2": "Walk it with the stories",
        "final_p": "Twenty-seven stops, two and a half hours, and a fisherman called Y'Own telling you why none of it is what it looks like.",
        "final_cta2": "Browse day trips",
    },

    "legal": {
        "privacy": '''<h2>Who runs this site</h2>
<p>reykjavikwalk.com is published by Touringbee Limited, a company registered in the Republic of Ireland, company number 660321. You can reach us at <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>
<h2>What we collect</h2>
<p>We do not ask you to create an account and we do not collect names, addresses or payment details on this site. If you buy the audio guide, the checkout is operated by Bókun and payment is processed by Stripe — your card details are handled by them, never by us.</p>
<p>Like almost every website, our host records standard server logs: IP address, browser type, the page you requested and the time. These are used to keep the site working and secure.</p>
<h2>Analytics and cookies</h2>
<p>We use privacy-respecting analytics to count page views and understand which guides are useful. We do not sell data and we do not run advertising networks on this site.</p>
<p>When you follow an affiliate link to a partner such as GetYourGuide, Tiqets or Booking.com, that partner may set a cookie in order to attribute a booking to us. Their cookie policies apply once you are on their site.</p>
<h2>The audio guide</h2>
<p>Purchases of the Reykjavík City Walking Tour are handled by Bókun (checkout) and TouringBee (delivery of your activation link). Their terms are at <a href="https://touringbee.com/terms-and-conditions-of-use/" target="_blank" rel="noopener">touringbee.com/terms-and-conditions-of-use</a>.</p>
<h2>Your rights</h2>
<p>If you are in the EU or UK you have the right to ask what personal data we hold about you, to have it corrected, and to have it deleted. Write to <a href="mailto:info@touringbee.com">info@touringbee.com</a> and we will respond within 30 days.</p>''',
        "affiliate": '''<p>Some of the links on reykjavikwalk.com are affiliate links. If you book or buy through one of them, we may earn a commission. It costs you nothing extra — the price is the same as going direct.</p>
<h2>Who we work with</h2>
<ul class="ticks">
<li><strong>GetYourGuide</strong> — day trips, Northern Lights tours, whale watching, transfers</li>
<li><strong>Tiqets</strong> — attraction and lagoon tickets</li>
<li><strong>Booking.com</strong> — hotels and car rental</li>
</ul>
<h2>Our own product</h2>
<p>The Reykjavík City Walking Tour audio guide is made by TouringBee, which publishes this site. We are not neutral about it — we think it is the best way to walk Reykjavík, and we say so. You can buy it here or directly from TouringBee at the same price.</p>
<h2>How this affects what we write</h2>
<p>Commission never decides what goes in a guide. We recommend the geothermal pools over the Blue Lagoon in several places even though the Blue Lagoon pays better, and we tell you which attractions are not worth the money. If a recommendation only exists because it pays, it is not a recommendation.</p>
<p>Prices, opening hours and availability change. Always confirm on the operator's own site before you travel.</p>
<p>Questions: <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>''',
    },
}
