# -*- coding: utf-8 -*-
"""Español (España) — tú. Sin «joya escondida», «imprescindible», «de ensueño»."""

G = [
    ("P0", "circulo-dorado", "Círculo Dorado desde Reikiavik", "Þingvellir, Geysir y Gullfoss en un día: en coche o con excursión."),
    ("P0", "blue-lagoon", "Blue Lagoon: entradas y traslados", "Cómo encajarlo entre vuelos y si el precio se sostiene."),
    ("P0", "auroras-boreales-reikiavik", "Auroras boreales en Reikiavik", "Temporada, previsión, sitios dentro de la ciudad y cuándo compensa una excursión."),
    ("P0", "hallgrimskirkja", "Hallgrímskirkja y su torre", "La iglesia, el ascensor, la cola y la hora buena para subir."),
    ("P0", "aeropuerto-keflavik-reikiavik", "Del aeropuerto de Keflavík al centro", "Flybus, traslado privado y coche de alquiler: precio y tiempo comparados."),
    ("P0", "sky-lagoon", "Sky Lagoon", "El spa geotermal a las puertas de la ciudad y su ritual de siete pasos."),
    ("P0", "avistamiento-ballenas-reikiavik", "Ballenas y frailecillos", "Barcos desde el puerto viejo, temporadas y mareo."),
    ("P0", "cuando-viajar-a-reikiavik", "Cuándo viajar a Reikiavik", "Luz, auroras, clima y precios, mes a mes."),
    ("P0", "un-dia-en-reikiavik", "Un día en Reikiavik", "La ruta a pie que hace caber lo esencial en una jornada."),
    ("P0", "que-ver-en-reikiavik", "Qué ver en Reikiavik", "La lista completa, ordenada por lo que merece tus horas de luz."),
    ("P1", "circulo-dorado-coche-o-excursion", "Círculo Dorado: ¿coche o excursión?", "Comparativa honesta de precio y tiempo."),
    ("P1", "excursiones-desde-reikiavik", "Excursiones desde Reikiavik", "Todas las que valen la pena, con tiempos de carretera."),
    ("P1", "costa-sur-islandia", "La costa sur en un día", "Seljalandsfoss, Skógafoss y la playa negra de Reynisfjara."),
    ("P1", "sun-voyager", "El Sun Voyager y el paseo marítimo", "La escultura que todo el mundo fotografía y lo que representa de verdad."),
    ("P1", "harpa", "Auditorio Harpa", "El panal de cristal y cómo sobrevivió al crac."),
    ("P1", "puerto-viejo-reikiavik", "El puerto viejo", "Barcos, comida, el buque guardacostas y las Guerras del Bacalao."),
    ("P1", "calle-arcoiris-laugavegur", "La calle arcoíris y Laugavegur", "La calle pintada y la arteria comercial."),
    ("P1", "perlan", "Perlan", "La cúpula, la cueva de hielo y el mirador."),
    ("P1", "dos-dias-en-reikiavik", "Dos días en Reikiavik", "Un plan más lento, con hueco para una laguna."),
    ("P1", "que-llevar-a-islandia", "Qué llevar y cómo vestirse", "Capas que aguantan un clima que cambia cada hora."),
    ("P1", "moverse-por-reikiavik", "Moverse por Reikiavik", "A pie, en autobús Strætó y cuándo necesitas coche."),
    ("P1", "precios-reikiavik", "¿Es cara Reikiavik?", "Lo que cuestan las cosas de verdad y dónde ahorrar."),
    ("P1", "donde-alojarse-en-reikiavik", "Dónde alojarse en Reikiavik", "Los barrios explicados y lo que pagas por cada uno."),
    ("P2", "arte-urbano-reikiavik", "Arte urbano en Reikiavik", "Los murales, incluido ese vampiro que nadie explica."),
    ("P2", "faro-de-grotta", "Grótta y los mejores sitios para auroras", "Dónde colocarte cuando el cielo se pone verde."),
    ("P2", "tjornin-austurvollur-parlamento", "Tjörnin, Austurvöllur y el Alþingi", "El estanque, la plaza y el parlamento más antiguo del mundo."),
    ("P2", "comida-islandesa", "Comida islandesa", "Pylsa, skyr, sopa de cordero, hákarl: qué probar y qué dejar."),
    ("P2", "piscinas-geotermales-reikiavik", "Piscinas geotermales y sus normas", "Las reglas de la ducha de las que nadie avisa al turista."),
    ("P2", "reikiavik-gratis", "Reikiavik gratis", "Un día entero que no cuesta nada."),
    ("P2", "museos-reikiavik", "Museos de Reikiavik", "El Museo Nacional, la exposición 871±2 y los más raros."),
]

CONTENT = {
    "slugs": {"guides": "guias", "privacy": "politica-de-privacidad",
              "affiliate": "aviso-de-afiliacion"},
    "guides": [{"wave": w, "slug": s, "title": t, "desc": d} for w, s, t, d in G],

    "ui": {
        "menu": "Guías", "menu_all": "Todas las guías",
        "buy": "Comprar la audioguía — 9,99 €",
        "see_tours": "Ver excursiones", "check_tickets": "Ver entradas",
        "sticky_title": "Reykjavík City Walking Tour — 9,99 €",
        "sticky_sub": "4,7 ★ · 27 paradas · sin conexión · en inglés",
        "sticky_btn": "Comprar",
        "rating_aria": "Valorado con 4,7 sobre 5",
        "rating_label": "valoración media de viajeros",
        "price_display": "9,99 €",
        "price_sub": "Pago único · sin suscripción · acceso 1 año",
        "checkout_note": "Pago seguro en esta página. ¿Prefieres la tienda?",
        "open_shop": "Abrir en TouringBee",
        "audio_fallback": "Tu navegador no reproduce audio.",
        "product_name": "Reykjavík City Walking Tour",
        "product_name_full": "Reykjavík City Walking Tour — audioguía por libre",
        "product_desc": "Un recorrido a pie por libre por Reikiavik con 27 paradas, audio y mapa GPS sin conexión, desde el monumento a Ingólfur Arnarson hasta Þúfa. Unas 2 a 2,5 horas.",
        "product_category": "Audioguía autoguiada",
        "author_h": "Sobre el autor",
        "author_alt": "Eugene, autor de las audioguías de TouringBee",
        "author_bio": "Eugene lleva dieciséis años viviendo en Francia, trabajó como guía y fundó la red de contenidos de viaje paris10.travel. Ha recorrido más de 300 pueblos y ciudades francesas y escribe las audioguías de TouringBee. Monta estas guías como quien informa a un amigo antes de un viaje: qué merece tu tiempo, qué conviene reservar y qué puedes saltarte.",
        "author_bio_plain": "Antiguo guía, fundador de paris10.travel, autor de las audioguías de TouringBee.",
        "f_explore": "Explorar", "f_product": "La audioguía", "f_legal": "Legal",
        "f_langs": "Idiomas", "f_alltours": "Todas las audioguías TouringBee",
        "f_terms": "Términos y condiciones",
        "langnames": {"en": "English", "fr": "Français", "de": "Deutsch", "es": "Español",
                      "it": "Italiano", "pt": "Português", "pl": "Polski", "ru": "Русский"},
        "disclaimer": "reykjavikwalk.com está publicado por Touringbee Limited (Irlanda, sociedad n.º 660321). Algunos enlaces de este sitio son de afiliación: si reservas a través de ellos, cobramos una comisión sin coste adicional para ti. Precios y horarios cambian; confirma siempre en la web oficial antes de viajar.",
        "guides_h1": "Todas las guías de Reikiavik",
        "guides_title": "Todas las guías de Reikiavik | TouringBee",
        "guides_meta": "Todas las guías de reykjavikwalk.com: Círculo Dorado, Blue Lagoon, auroras boreales, Hallgrímskirkja, traslados del aeropuerto, itinerarios y más.",
        "guides_lead": 'Treinta guías sobre Reikiavik y las excursiones que salen de ahí, publicadas por tandas. Empieza por la <a href="/es/">guía completa de Reikiavik</a>: todo lo de abajo profundiza en una pieza concreta.',
        "in_production": "En preparación",
        "waves": {"P0": "Primera tanda — en escritura",
                  "P1": "Segunda tanda", "P2": "Tercera tanda"},
        "updated": "Última actualización: 6 de agosto de 2026",
        "privacy_title": "Política de privacidad",
        "privacy_meta": "Cómo trata reykjavikwalk.com los datos, las cookies y el seguimiento de afiliación.",
        "affiliate_title": "Aviso de afiliación",
        "affiliate_meta": "Qué enlaces de reykjavikwalk.com son de afiliación, con quién trabajamos y en qué afecta a nuestras recomendaciones.",
        "nf_h1": "Esta página no está",
        "nf_p": "O todavía no se ha publicado, o el enlace está mal. Las dos cosas tienen arreglo.",
        "nf_cta1": "Guía completa de Reikiavik",
    },

    "home": {
        "city": "Reikiavik",
        "city_desc": "La capital de Islandia y la capital más septentrional del mundo.",
        "title": "Qué ver en Reikiavik: ruta a pie y excursiones | TouringBee",
        "meta": "Prepara Reikiavik en serio: una ruta a pie por libre de 27 paradas con audio sin conexión, más el Círculo Dorado, el Blue Lagoon, las auroras boreales y todo lo que mejor hace la capital más al norte del mundo.",
        "hero_alt": "La escultura Sun Voyager en el paseo marítimo de Reikiavik bajo un cielo islandés enorme",
        "chip": "27 paradas · 2–2,5 horas · funciona sin conexión",
        "h1": "Reikiavik a pie, a tu ritmo",
        "sub": "La capital más al norte del mundo se recorre en una tarde a pie, siempre que sepas qué estás mirando. Esta es la guía completa: el recorrido, las excursiones que sí conviene reservar y las estaciones, que lo cambian todo.",
        "cta_inside": "Ver qué incluye", "cta_preview": "Escuchar un fragmento",
        "cta_daytrips": "Excursiones",
        "intro1": "Reikiavik es pequeña. Unos 140.000 habitantes, un centro antiguo que cruzas en veinte minutos y casi todo lo que has venido a ver está en ese trayecto. Lo demás, a veinte minutos en autobús.",
        "intro2": "Ahí está la trampa. Parece una ciudad que se «hace» en una mañana. Así que la gente fotografía la iglesia, fotografía el Sun Voyager y se marcha. Sin haber oído cómo un país de pescadores derrotó a la Royal Navy. Ni por qué en 2013 desviaron una carretera ya trazada: los vecinos habían salido en defensa de los elfos.",
        "intro3": 'Lo que importa son las historias. Por eso hicimos el <a href="#audio">Reykjavík City Walking Tour</a>: 27 paradas, desde la estatua del fundador de la ciudad hasta un montículo de hierba junto al puerto, con una caseta de secar pescado encima. Le das al play, caminas y paras donde quieras. Dos horas y media. O toda la tarde, si te detienes a por café. Cosa que harás.',
        "preview_h": "Escucha el arranque",
        "preview_p": "30 segundos de la introducción, en inglés",
        "highlights": [("El recorrido", "De Arnarhóll a Þúfa, 27 paradas numeradas"),
                       ("Funciona en", "iPhone y Android, totalmente sin conexión"),
                       ("El ritmo", "El tuyo: pausa, desvío, continúas"),
                       ("Acceso", "Un pago, un año")],
        "prod_h2": "El Reykjavík City Walking Tour",
        "prod_lead": "Escrito por periodistas e historiadores, narrado por Y'Own: un pescador de Reikiavik con tiempo de sobra antes de volver a salir al mar.",
        "prod_alt": "La app de TouringBee con la ruta de Reikiavik, sostenida frente a Hallgrímskirkja",
        "ticks": ["<strong>27 paradas de audio</strong>: Hallgrímskirkja, el Sun Voyager, Harpa, el museo del punk, el ICGV Óðinn, Þúfa y más",
                  "<strong>Mapa GPS sin conexión</strong> que muestra dónde estás; la grabación la lanzas tú al llegar al punto",
                  "<strong>Ilustraciones</strong> para saber qué edificio tienes delante",
                  "<strong>Entrega inmediata</strong>: el correo de activación llega en unos minutos",
                  "<strong>Sin grupo ni horario</strong>: empiezas el día y la hora que quieras"],
        "why_h2": "Por qué Reikiavik merece más que una escala",
        "why_p1": "Hace mil años, un noruego llamado Ingólfur Arnarson tiró por la borda los maderos labrados de su asiento de honor y dejó que los dioses eligieran dónde viviría. Sus esclavos tardaron tres años en encontrarlos, varados en una bahía llena de vapor. La llamó <em>Reykjavík</em>, bahía humeante. Ese vapor sigue siendo el motivo de que aquí el agua de la ducha huela a azufre.",
        "why_p2": "Islandia se pasó los mil años siguientes gobernada por otros. Noruega, luego Dinamarca, luego un monopolio comercial dirigido desde Copenhague que asfixió la economía durante dos siglos. La independencia llegó por fases y no se completó hasta 1944. Eso cabe en la memoria de una sola generación, y se nota: es un país que todavía se sorprende un poco de gobernarse solo.",
        "why_img1_alt": "La casa de gobierno de Reikiavik con una estatua delante",
        "why_img2_alt": "Una visitante pasa junto al Sun Voyager en el paseo de Sæbraut en invierno",
        "light_h3": "Aquí manda la luz",
        "light_p1": "Nada condiciona tanto una visita a Reikiavik como el cielo. Entre mayo y julio el sol casi no se molesta en ponerse y la ciudad se queda despierta con él. En noviembre y diciembre tienes cuatro o cinco horas de luz aprovechable, y todo lo que planeaste tiene que caber ahí.",
        "light_p2": "A cambio están las auroras. De septiembre a abril, más o menos, en una noche oscura y despejada se ven desde dentro de la ciudad: el faro de Grótta y el paseo de Sæbraut son los sitios de siempre. Ni la temporada ni una excursión garantizan nada. Un cielo limpio sí.",
        "light_link": ("cuando-viajar-a-reikiavik", "Cuándo venir"),
        "free_h3": "Casi todo es gratis",
        "free_p": "El recorrido no cuesta nada. El centro de Reikiavik es un museo al aire libre: los murales, el puerto, el estanque, el parlamento, la calle arcoíris. Lo de pago se cuenta con los dedos de una mano: el ascensor de la torre de Hallgrímskirkja, Perlan, los museos y las piscinas geotermales — unos cientos de coronas, y bien invertidas. Guárdate el presupuesto para las excursiones. Ahí es donde Islandia se pone cara.",
        "free_link": ("precios-reikiavik", "Lo que cuesta Reikiavik de verdad"),
        "weird_h3": "Una ciudad a la que no le avergüenza ser rara",
        "weird_p1": "Reikiavik tiene un museo del falo, un museo del punk montado en unos antiguos baños públicos, un mural de un vampiro y una locomotora de vapor que nunca tuvo vías por donde circular. Durante diecisiete años la televisión paraba en julio para que la gente saliera a la calle. Y una vez la ciudad tumbó a un gobierno a golpe de cacerola.",
        "weird_p2": "En las postales no sale nada de esto. En el recorrido está todo.",
        "weird_img_alt": "La locomotora de vapor conservada junto al puerto viejo de Reikiavik",
        "oneday_link": ("un-dia-en-reikiavik", "Ver el plan de un día"),
        "tiles_h2": "Lo que verás por el camino",
        "tiles_lead": "Seis de las veintisiete paradas. El resto lo irás encontrando por el camino.",
        "tiles": [
            {"href": "hallgrimskirkja", "img": "tile-hallgrimskirkja", "h": "Hallgrímskirkja",
             "alt": "La iglesia Hallgrímskirkja vista desde abajo con la bandera islandesa ondeando",
             "p": "La iglesia de columnas de basalto y, desde su torre, la mejor vista de la ciudad"},
            {"href": "calle-arcoiris-laugavegur", "img": "tile-rainbow-street", "h": "La calle arcoíris",
             "alt": "Skólavörðustígur, la calle pintada de arcoíris que sube hacia Hallgrímskirkja",
             "p": "Skólavörðustígur, pintada para el Orgullo y nunca borrada"},
            {"href": "harpa", "img": "tile-harpa", "h": "Harpa",
             "alt": "La fachada de panal de cristal del auditorio Harpa al atardecer",
             "p": "Un panal de cristal levantado en plena crisis que casi se lo lleva por delante"},
            {"href": "puerto-viejo-reikiavik", "img": "tile-old-harbour", "h": "El puerto viejo",
             "alt": "Barcos pesqueros amarrados en el puerto viejo de Reikiavik",
             "p": "De aquí salen los barcos de ballenas, y aquí se ganaron las Guerras del Bacalao"},
            {"href": "que-ver-en-reikiavik", "img": "tile-whales", "h": "Whales of Iceland",
             "alt": "Ballenas a tamaño real iluminadas de azul en la exposición Whales of Iceland",
             "p": "Veintitrés ballenas a tamaño real en una nave a oscuras junto al agua"},
            {"href": "que-ver-en-reikiavik", "img": "tile-thufa", "h": "Þúfa",
             "alt": "Þúfa, el montículo en espiral cubierto de hierba con su caseta de secar pescado",
             "p": "El final del recorrido: una colina en espiral con un secadero de pescado arriba"}],
        "how_h2": "Cómo funciona la audioguía",
        "steps": [{"h": "Compra", "p": "Un pago en esta página. El correo de activación llega en unos minutos."},
                  {"h": "Descarga", "p": "Instala la app gratuita de TouringBee, actívala y descarga el recorrido con el wifi del hotel."},
                  {"h": "Camina", "p": "El mapa sin conexión muestra dónde estás. Al llegar a una parada le das al play: la app nunca te interrumpe sola."},
                  {"h": "Consérvala", "p": "Un año de acceso. Vuelve en invierno y haz la misma ruta a oscuras."}],
        "how_note": "Lleva auriculares. El viento islandés puede más que el altavoz del móvil.",
        "basics_h2": "Reikiavik: lo básico",
        "facts": [("Llegar", "Keflavík (KEF), ~45 min en Flybus o en coche"),
                  ("Moneda", "Corona islandesa (ISK): tarjeta en todas partes, efectivo casi nunca"),
                  ("Moverse", "A pie por el centro, autobuses Strætó, coche para las excursiones"),
                  ("Idioma", "Islandés; el inglés se habla prácticamente en todos lados"),
                  ("Temporada de auroras", "~septiembre a abril, solo noches oscuras y despejadas"),
                  ("Sol de medianoche", "~mayo a julio, casi sin oscuridad real"),
                  ("Clima", "Cambia cada hora. Capas impermeables mejor que paraguas"),
                  ("Agua del grifo", "Excelente y gratis. No compres agua embotellada aquí")],
        "book_h3": "Reserva antes lo que se paga",
        "book_p": "Reikiavik rara vez se agota, pero aquello por lo que la gente coge un avión sí: Blue Lagoon, Sky Lagoon, barcos de auroras y el Círculo Dorado en verano. Reservar antes también evita tener que rehacer el paseo por culpa de una cola.",
        "book_cta": "Entradas de Reikiavik en Tiqets",
        "partners_h2": "Excursiones y entradas",
        "partners_lead": "El recorrido cubre la ciudad. Todo lo que viene ahora queda fuera de ella, y son las reservas que conviene cerrar antes de aterrizar.",
        "p_golden_h": "Círculo Dorado",
        "p_golden_p": "Tres paradas, un día largo: el circuito islandés clásico y el más concurrido.",
        "p_blue_p": "Cerca del aeropuerto, así que funciona como primera o última parada. Los horarios vuelan.",
        "p_blue_alt": "El spa geotermal Blue Lagoon con vapor sobre un agua azul lechosa",
        "p_aurora_h": "Auroras boreales",
        "p_aurora_p": "Barcos y microbuses que persiguen el cielo despejado. La mayoría te recoloca gratis si se nubla.",
        "p_aurora_alt": "Auroras boreales verdes sobre una carretera cerca de Reikiavik",
        "p_sky_p": "La alternativa urbana al Blue Lagoon: más cerca, más barata de alcanzar, mismo vapor.",
        "p_sky_alt": "Una laguna geotermal iluminada de azul al anochecer cerca de Reikiavik",
        "car_h3": "¿Conduces tú? Reserva pronto",
        "car_p": "El Círculo Dorado y la costa sur se disfrutan más al volante: paras donde quieres y te libras del horario del autocar. La flota de alquiler islandesa es pequeña y en verano se agota con semanas de antelación. Es una de las pocas reservas que de verdad hay que cerrar antes de volar.",
        "car_cta": "Comparar coches de alquiler",
        "car_link": ("circulo-dorado-coche-o-excursion", "¿Coche o excursión?"),
        "cross_h2": "Otros paseos con audio de TouringBee",
        "cross_lead": "Islandia comerció con Copenhague durante dos siglos, y no por gusto. El recorrido cuenta esa historia; ya puestos, escucha la otra versión.",
        "cross": [{"h": "Copenhague", "path": "product/copenhagen-city-tour",
                   "p": "La ciudad que manejó la economía islandesa doscientos años, recorrida en unas tres horas.",
                   "cta": "Copenhagen Walking Tour"},
                  {"h": "Oslo", "path": "product/oslo-city-tour",
                   "p": "De ahí salió Ingólfur Arnarson, más o menos, y ahí empiezan las sagas.",
                   "cta": "Oslo City Walking Tour"},
                  {"h": "Todo el catálogo", "path": "shop-tbee",
                   "p": "Un centenar de paseos con audio por libre, en Europa y fuera de ella.",
                   "cta": "Ver la tienda"}],
        "plan_h2": "Prepara tu visita",
        "plan": [{"h": "Llegar", "links": [("aeropuerto-keflavik-reikiavik", "Aeropuerto de Keflavík"), ("moverse-por-reikiavik", "Moverse por la ciudad")]},
                 {"h": "Excursiones", "links": [("circulo-dorado", "Círculo Dorado"), ("costa-sur-islandia", "Costa sur"), ("excursiones-desde-reikiavik", "Todas las excursiones")]},
                 {"h": "Cuándo", "links": [("cuando-viajar-a-reikiavik", "Cuándo viajar"), ("que-llevar-a-islandia", "Qué llevar"), ("auroras-boreales-reikiavik", "Auroras boreales")]},
                 {"h": "En la ciudad", "links": [("hallgrimskirkja", "Hallgrímskirkja"), ("perlan", "Perlan"), ("arte-urbano-reikiavik", "Arte urbano")]},
                 {"h": "Agua", "links": [("blue-lagoon", "Blue Lagoon"), ("sky-lagoon", "Sky Lagoon"), ("piscinas-geotermales-reikiavik", "Piscinas de la ciudad")]},
                 {"h": "Práctico", "links": [("precios-reikiavik", "Lo que cuesta"), ("donde-alojarse-en-reikiavik", "Dónde alojarse"), ("comida-islandesa", "Qué comer")]}],
        "faq_h2": "Preguntas frecuentes",
        "faq": [
            ("¿Cuántos días hacen falta en Reikiavik?", "Dos días completos cubren la ciudad con holgura: uno para el paseo y los museos, otro para una laguna o el puerto. Suma un día por cada excursión grande: uno para el Círculo Dorado, otro para la costa sur. Casi todo el mundo subestima el tiempo que un viaje a Islandia se pasa dentro de un vehículo."),
            ("¿Se recorre el centro a pie?", "Entero. Las 27 paradas suman unos 5 km casi sin desnivel, salvo la cuesta de Skólavörðustígur hasta la iglesia. El límite lo pone el tiempo, no la distancia."),
            ("¿La audioguía se activa sola mientras camino?", "No, y es intencionado. El mapa sin conexión muestra dónde estás, pero el play lo das tú al llegar a la parada. La precisión del GPS de un móvil varía demasiado para que el disparo automático sea fiable. En manual no te pierdes una historia porque el teléfono creyera que estabas en la calle de al lado."),
            ("¿Necesito datos móviles durante el paseo?", "No. Descarga el recorrido una vez con wifi y funciona entero sin conexión, mapa incluido."),
            ("¿Se ven las auroras desde dentro de Reikiavik?", "Sí, en una noche oscura y despejada entre septiembre y abril aproximadamente. El faro de Grótta, en Seltjarnarnes, y el tramo oscuro del paseo de Sæbraut son los sitios habituales. La contaminación lumínica del centro juega en contra y las nubes ganan siempre: ninguna temporada ni excursión puede prometerte una aurora."),
            ("¿Es cara Reikiavik?", "Comer fuera y el alcohol, sí, bastante. La ciudad en sí no: el paseo, el puerto, los murales y los parques son gratis, el agua del grifo es excelente y las piscinas geotermales cuestan una fracción del Blue Lagoon. El presupuesto se va en excursiones y cenas."),
            ("¿Cómo hay que vestirse?", "Chubasquero, capa térmica, calzado que no resbale y gorro, en cualquier mes. El paraguas no sirve: el viento de Reikiavik lo destroza, y los locales lo notan."),
            ("¿La audioguía está en español?", "El Reykjavík City Walking Tour se narra de momento en inglés. Otros recorridos de TouringBee están disponibles en ocho idiomas."),
        ],
        "final_h2": "Recórrela y escucha por qué",
        "final_p": "Veintisiete paradas, dos horas y media, y un pescador llamado Y'Own explicándote por qué nada de esto es lo que parece.",
        "final_cta2": "Ver excursiones",
    },

    "legal": {
        "privacy": '''<h2>Quién edita este sitio</h2>
<p>reykjavikwalk.com está publicado por Touringbee Limited, sociedad registrada en la República de Irlanda con el número 660321. Escríbenos a <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>
<h2>Qué recogemos</h2>
<p>No hay que crear cuenta y no recogemos nombres, direcciones ni datos de pago en este sitio. Si compras la audioguía, la caja la opera Bókun y el pago lo procesa Stripe: tus datos de tarjeta los tratan ellos, nunca nosotros.</p>
<p>Como casi cualquier web, nuestro alojamiento guarda registros de servidor estándar: dirección IP, tipo de navegador, página solicitada y hora. Sirven para que el sitio funcione y esté seguro.</p>
<h2>Analítica y cookies</h2>
<p>Usamos analítica respetuosa con la privacidad para contar visitas y saber qué guías resultan útiles. No vendemos datos ni ponemos redes publicitarias.</p>
<p>Cuando sigues un enlace de afiliación hacia un socio como GetYourGuide, Tiqets o Booking.com, ese socio puede instalar una cookie para atribuirnos la reserva. Desde ese momento se aplica su política.</p>
<h2>La audioguía</h2>
<p>Las compras del Reykjavík City Walking Tour las gestionan Bókun (pago) y TouringBee (envío del enlace de activación). Sus condiciones: <a href="https://touringbee.com/terms-and-conditions-of-use/" target="_blank" rel="noopener">touringbee.com/terms-and-conditions-of-use</a>.</p>
<h2>Tus derechos</h2>
<p>En la UE y el Reino Unido puedes pedir qué datos personales tenemos, corregirlos o eliminarlos. Escribe a <a href="mailto:info@touringbee.com">info@touringbee.com</a> y respondemos en un plazo de 30 días.</p>''',
        "affiliate": '''<p>Algunos enlaces de reykjavikwalk.com son de afiliación. Si reservas o compras a través de ellos, cobramos una comisión. A ti no te cuesta nada más: el precio es el mismo que yendo directo.</p>
<h2>Con quién trabajamos</h2>
<ul class="ticks">
<li><strong>GetYourGuide</strong> — excursiones, auroras boreales, avistamiento de ballenas, traslados</li>
<li><strong>Tiqets</strong> — entradas de atracciones y lagunas</li>
<li><strong>Booking.com</strong> — hoteles y alquiler de coches</li>
</ul>
<h2>Nuestro propio producto</h2>
<p>La audioguía Reykjavík City Walking Tour la hace TouringBee, que edita este sitio. No somos neutrales: creemos que es la mejor forma de recorrer Reikiavik y lo decimos. Puedes comprarla aquí o directamente en TouringBee, al mismo precio.</p>
<h2>En qué afecta a lo que escribimos</h2>
<p>La comisión nunca decide el contenido de una guía. Recomendamos varias veces las piscinas geotermales antes que el Blue Lagoon, aunque el Blue Lagoon pague mejor, y decimos qué atracciones no valen lo que cuestan. Una recomendación que solo existe porque paga no es una recomendación.</p>
<p>Precios, horarios y disponibilidad cambian. Confirma siempre en la web del operador antes de viajar.</p>
<p>Dudas: <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>''',
    },
}
