# -*- coding: utf-8 -*-
"""Italiano — tu. Niente «gemma nascosta», «da non perdere», «mozzafiato»."""

G = [
    ("P0", "circolo-doro", "Circolo d'Oro da Reykjavik", "Þingvellir, Geysir e Gullfoss in un giorno: in auto o in escursione."),
    ("P0", "blue-lagoon", "Blue Lagoon: biglietti e transfer", "Come incastrarla tra i voli e se il prezzo regge."),
    ("P0", "aurora-boreale-reykjavik", "Aurora boreale a Reykjavik", "Stagione, previsioni, punti in città e quando l'escursione serve davvero."),
    ("P0", "hallgrimskirkja", "Hallgrímskirkja e la torre", "La chiesa, l'ascensore, la fila e l'ora giusta per salire."),
    ("P0", "aeroporto-keflavik-reykjavik", "Dall'aeroporto di Keflavík al centro", "Flybus, transfer privato, noleggio: costi e tempi a confronto."),
    ("P0", "sky-lagoon", "Sky Lagoon", "La spa geotermale alle porte della città e il suo rituale in sette passaggi."),
    ("P0", "avvistamento-balene-reykjavik", "Balene e pulcinella di mare", "Le barche dal porto vecchio, le stagioni e il mal di mare."),
    ("P0", "quando-andare-a-reykjavik", "Quando andare a Reykjavik", "Luce, aurore, meteo e prezzi, mese per mese."),
    ("P0", "un-giorno-a-reykjavik", "Un giorno a Reykjavik", "L'itinerario a piedi che fa entrare l'essenziale in una giornata."),
    ("P0", "cosa-vedere-a-reykjavik", "Cosa vedere a Reykjavik", "La lista completa, ordinata per quanto vale le tue ore di luce."),
    ("P1", "circolo-doro-auto-o-tour", "Circolo d'Oro: auto o tour?", "Confronto onesto su costi e tempi."),
    ("P1", "escursioni-da-reykjavik", "Escursioni da Reykjavik", "Tutte quelle che valgono il viaggio, con i tempi di guida."),
    ("P1", "costa-sud-islanda", "La costa sud in un giorno", "Seljalandsfoss, Skógafoss e la spiaggia nera di Reynisfjara."),
    ("P1", "sun-voyager", "Il Sun Voyager e il lungomare", "La scultura che fotografano tutti, e cosa rappresenta davvero."),
    ("P1", "harpa", "Auditorium Harpa", "L'alveare di vetro, e come è sopravvissuto al crac."),
    ("P1", "porto-vecchio-reykjavik", "Il porto vecchio", "Barche, cibo, la nave della guardia costiera e le Guerre del merluzzo."),
    ("P1", "via-arcobaleno-laugavegur", "La via arcobaleno e Laugavegur", "La strada dipinta e l'arteria dello shopping."),
    ("P1", "perlan", "Perlan", "La cupola, la grotta di ghiaccio e la terrazza panoramica."),
    ("P1", "due-giorni-a-reykjavik", "Due giorni a Reykjavik", "Un piano più lento, con spazio per una laguna."),
    ("P1", "cosa-mettere-in-valigia-islanda", "Cosa mettere in valigia", "Gli strati che reggono un meteo che cambia ogni ora."),
    ("P1", "muoversi-a-reykjavik", "Muoversi a Reykjavik", "A piedi, con i bus Strætó, e quando serve l'auto."),
    ("P1", "prezzi-reykjavik", "Reykjavik è cara?", "Quanto costano davvero le cose e dove risparmiare."),
    ("P1", "dove-dormire-a-reykjavik", "Dove dormire a Reykjavik", "I quartieri spiegati, e cosa paghi per ciascuno."),
    ("P2", "street-art-reykjavik", "Street art a Reykjavik", "I murales, compreso quel vampiro che nessuno spiega."),
    ("P2", "faro-di-grotta", "Grótta e i posti migliori per l'aurora", "Dove metterti quando il cielo diventa verde."),
    ("P2", "tjornin-austurvollur-parlamento", "Tjörnin, Austurvöllur e l'Alþingi", "Il laghetto, la piazza e il parlamento più antico del mondo."),
    ("P2", "cucina-islandese", "Cucina islandese", "Pylsa, skyr, zuppa d'agnello, hákarl: cosa provare e cosa lasciare."),
    ("P2", "piscine-geotermali-reykjavik", "Piscine geotermali e galateo", "Le regole della doccia di cui nessuno avverte i turisti."),
    ("P2", "reykjavik-gratis", "Reykjavik gratis", "Una giornata intera che non costa nulla."),
    ("P2", "musei-reykjavik", "I musei di Reykjavik", "Museo Nazionale, mostra 871±2 e quelli più strani."),
]

CONTENT = {
    "slugs": {"guides": "guide", "privacy": "privacy",
              "affiliate": "avviso-affiliazione"},
    "guides": [{"wave": w, "slug": s, "title": t, "desc": d} for w, s, t, d in G],

    "ui": {
        "menu": "Guide", "menu_all": "Tutte le guide",
        "buy": "Acquista l'audioguida — 9,99 €",
        "see_tours": "Vedi le escursioni", "check_tickets": "Vedi i biglietti",
        "sticky_title": "Reykjavík City Walking Tour — 9,99 €",
        "sticky_sub": "4,7 ★ · 27 tappe · offline · in inglese",
        "sticky_btn": "Acquista",
        "rating_aria": "Valutato 4,7 su 5",
        "rating_label": "valutazione media dei viaggiatori",
        "price_display": "9,99 €",
        "price_sub": "Pagamento unico · nessun abbonamento · accesso 1 anno",
        "checkout_note": "Pagamento sicuro su questa pagina. Preferisci lo shop?",
        "open_shop": "Aprilo su TouringBee",
        "audio_fallback": "Il tuo browser non riproduce l'audio.",
        "product_name": "Reykjavík City Walking Tour",
        "product_name_full": "Reykjavík City Walking Tour — audioguida in autonomia",
        "product_desc": "Una passeggiata in autonomia per Reykjavik in 27 tappe, con audio e mappa GPS offline, dal monumento a Ingólfur Arnarson fino a Þúfa. Circa 2-2,5 ore.",
        "product_category": "Audioguida in autonomia",
        "author_h": "L'autore",
        "author_alt": "Eugene, autore delle audioguide TouringBee",
        "author_bio": "Eugene vive in Francia da sedici anni, ha lavorato come guida e ha fondato la rete di contenuti di viaggio paris10.travel. Ha visitato più di 300 città e paesi francesi e scrive le audioguide TouringBee. Costruisce queste guide come se dovesse preparare un amico prima di una partenza: cosa merita davvero il tuo tempo, cosa prenotare e cosa saltare.",
        "author_bio_plain": "Ex guida, fondatore di paris10.travel, autore delle audioguide TouringBee.",
        "f_explore": "Esplora", "f_product": "L'audioguida", "f_legal": "Note legali",
        "f_langs": "Lingue", "f_alltours": "Tutte le audioguide TouringBee",
        "f_terms": "Termini e condizioni",
        "langnames": {"en": "English", "fr": "Français", "de": "Deutsch", "es": "Español",
                      "it": "Italiano", "pt": "Português", "pl": "Polski", "ru": "Русский"},
        "disclaimer": "reykjavikwalk.com è pubblicato da Touringbee Limited (Irlanda, società n. 660321). Alcuni link di questo sito sono affiliati: se prenoti tramite loro riceviamo una commissione, senza costi aggiuntivi per te. Prezzi e orari cambiano: verifica sempre sul sito ufficiale prima di partire.",
        "guides_h1": "Tutte le guide su Reykjavik",
        "guides_title": "Tutte le guide su Reykjavik | TouringBee",
        "guides_meta": "Tutte le guide di reykjavikwalk.com: Circolo d'Oro, Blue Lagoon, aurora boreale, Hallgrímskirkja, transfer dall'aeroporto, itinerari e altro.",
        "guides_lead": 'Trenta guide su Reykjavik e sulle escursioni che partono da lì, pubblicate a ondate. Parti dalla <a href="/it/">guida completa di Reykjavik</a>: tutto quello che segue approfondisce un singolo pezzo.',
        "in_production": "In preparazione",
        "waves": {"P0": "Prima ondata — in scrittura",
                  "P1": "Seconda ondata", "P2": "Terza ondata"},
        "updated": "Ultimo aggiornamento: 6 agosto 2026",
        "privacy_title": "Informativa sulla privacy",
        "privacy_meta": "Come reykjavikwalk.com tratta dati, cookie e tracciamento di affiliazione.",
        "affiliate_title": "Avviso di affiliazione",
        "affiliate_meta": "Quali link di reykjavikwalk.com sono affiliati, con chi lavoriamo e cosa cambia nelle nostre raccomandazioni.",
        "nf_h1": "Questa pagina non c'è",
        "nf_p": "O non è ancora pubblicata, o il link è sbagliato. Si risolve in entrambi i casi.",
        "nf_cta1": "Guida completa di Reykjavik",
    },

    "home": {
        "city": "Reykjavik",
        "city_desc": "La capitale dell'Islanda e la capitale più a nord del mondo.",
        "title": "Cosa vedere a Reykjavik: passeggiata e escursioni | TouringBee",
        "meta": "Prepara Reykjavik sul serio: una passeggiata in autonomia di 27 tappe con audio offline, più Circolo d'Oro, Blue Lagoon, aurora boreale e tutto quello che la capitale più a nord del mondo sa fare meglio.",
        "hero_alt": "La scultura Sun Voyager sul lungomare di Reykjavik sotto un cielo islandese enorme",
        "chip": "27 tappe · 2-2,5 ore · funziona offline",
        "h1": "Reykjavik a piedi, con i tuoi tempi",
        "sub": "La capitale più a nord del mondo si gira in un pomeriggio a piedi, a patto di sapere cosa stai guardando. Questa è la guida completa: la passeggiata, le escursioni che vale la pena prenotare e le stagioni, che cambiano tutto.",
        "cta_inside": "Cosa contiene", "cta_preview": "Ascolta un estratto",
        "cta_daytrips": "Escursioni",
        "intro1": "Reykjavik è piccola. Circa 140.000 abitanti, un centro storico che attraversi in venti minuti e quasi tutto quello per cui sei venuto sta su quel percorso. Il resto è a venti minuti di autobus.",
        "intro2": "Ed è proprio la trappola. Sembra una città che si «fa» in una mattina. Così si fotografa la chiesa, si fotografa il Sun Voyager e si riparte. Senza aver mai sentito come un popolo di pescatori abbia battuto la Royal Navy. Né perché nel 2013 abbiano spostato una strada già progettata: i residenti avevano preso le parti degli elfi.",
        "intro3": 'Quello che conta sono le storie. Per questo abbiamo fatto il <a href="#audio">Reykjavík City Walking Tour</a>: 27 tappe, dalla statua del fondatore della città a una collinetta d\'erba vicino al porto, con sopra un essiccatoio per il pesce. Premi play, cammini, ti fermi dove vuoi. Due ore e mezza. O un pomeriggio intero, se continui a fermarti per un caffè. E lo farai.',
        "preview_h": "Ascolta l'inizio",
        "preview_p": "30 secondi dell'introduzione, in inglese",
        "highlights": [("Il percorso", "Da Arnarhóll a Þúfa, 27 tappe numerate"),
                       ("Funziona su", "iPhone e Android, completamente offline"),
                       ("Il ritmo", "Il tuo: pausa, deviazione, si riparte"),
                       ("Accesso", "Un pagamento, un anno")],
        "prod_h2": "Il Reykjavík City Walking Tour",
        "prod_lead": "Scritto da giornalisti e storici, raccontato da Y'Own: un pescatore di Reykjavik con del tempo davanti prima di rimettersi in mare.",
        "prod_alt": "L'app TouringBee con il percorso di Reykjavik, tenuta davanti a Hallgrímskirkja",
        "ticks": ["<strong>27 tappe audio</strong>: Hallgrímskirkja, il Sun Voyager, Harpa, il museo del punk, l'ICGV Óðinn, Þúfa e altro",
                  "<strong>Mappa GPS offline</strong> che mostra dove sei; la registrazione la avvii tu quando arrivi sul posto",
                  "<strong>Illustrazioni</strong> per capire quale edificio hai davanti",
                  "<strong>Consegna immediata</strong>: la mail di attivazione arriva in pochi minuti",
                  "<strong>Nessun gruppo, nessun orario</strong>: parti il giorno e l'ora che vuoi"],
        "why_h2": "Perché Reykjavik merita più di uno scalo",
        "why_p1": "Mille anni fa un norvegese di nome Ingólfur Arnarson gettò in mare i montanti intagliati del suo seggio d'onore e lasciò decidere agli dèi dove sarebbe vissuto. I suoi schiavi ci misero tre anni a ritrovarli, spiaggiati in una baia piena di vapore. La chiamò <em>Reykjavík</em>, baia fumante. Quel vapore è ancora il motivo per cui qui l'acqua della doccia sa di zolfo.",
        "why_p2": "Per i mille anni successivi l'Islanda fu governata da altri. Prima la Norvegia, poi la Danimarca, poi un monopolio commerciale gestito da Copenaghen, che ha strozzato l'economia per due secoli. L'indipendenza è arrivata a tappe e si è completata solo nel 1944. È memoria viva, e si sente: questo è un paese che ancora si stupisce un po' di governarsi da solo.",
        "why_img1_alt": "Il palazzo del governo a Reykjavik con una statua davanti",
        "why_img2_alt": "Una visitatrice passa accanto al Sun Voyager sul lungomare di Sæbraut d'inverno",
        "light_h3": "Qui comanda la luce",
        "light_p1": "Niente condiziona una visita a Reykjavik quanto il cielo. Tra maggio e luglio il sole quasi non tramonta e la città resta sveglia con lui. A novembre e dicembre hai quattro o cinque ore di luce utile, e tutto quello che avevi in programma deve starci dentro.",
        "light_p2": "In cambio arriva l'aurora. Grosso modo da settembre ad aprile, in una notte buia e limpida, si vede anche dalla città: il faro di Grótta e il lungomare di Sæbraut sono i posti classici. Né la stagione né un'escursione garantiscono niente. Un cielo sgombro sì.",
        "light_link": ("quando-andare-a-reykjavik", "Quando venire"),
        "free_h3": "Quasi tutto è gratis",
        "free_p": "La passeggiata non costa nulla. Il centro di Reykjavik è un museo all'aperto: i murales, il porto, il laghetto, il parlamento, la via arcobaleno. Si paga per poche cose: l'ascensore della torre di Hallgrímskirkja, Perlan, i musei e le piscine geotermali — qualche centinaio di corone, spese bene. Tieni da parte il budget per le escursioni. È lì che l'Islanda diventa cara.",
        "free_link": ("prezzi-reykjavik", "Quanto costa davvero Reykjavik"),
        "weird_h3": "Una città che non si vergogna di essere strana",
        "weird_p1": "Reykjavik ha un museo del fallo, un museo del punk ricavato in vecchi bagni pubblici, un murale con un vampiro e una locomotiva a vapore che non ha mai avuto una ferrovia su cui correre. Per diciassette anni la televisione si fermava a luglio, così la gente usciva di casa. E una volta la città ha fatto cadere un governo a colpi di pentole.",
        "weird_p2": "Sulle cartoline non c'è niente di tutto questo. Sul percorso c'è tutto.",
        "weird_img_alt": "La locomotiva a vapore conservata vicino al porto vecchio di Reykjavik",
        "oneday_link": ("un-giorno-a-reykjavik", "Vedi il piano di un giorno"),
        "tiles_h2": "Cosa vedrai lungo il percorso",
        "tiles_lead": "Sei tappe su ventisette. Le altre le incontri camminando.",
        "tiles": [
            {"href": "hallgrimskirkja", "img": "tile-hallgrimskirkja", "h": "Hallgrímskirkja",
             "alt": "La chiesa Hallgrímskirkja vista dal basso con la bandiera islandese al vento",
             "p": "La chiesa a colonne di basalto e, dalla torre, la vista migliore sulla città"},
            {"href": "via-arcobaleno-laugavegur", "img": "tile-rainbow-street", "h": "La via arcobaleno",
             "alt": "Skólavörðustígur, la strada dipinta ad arcobaleno che sale verso Hallgrímskirkja",
             "p": "Skólavörðustígur, dipinta per il Pride e mai più cancellata"},
            {"href": "harpa", "img": "tile-harpa", "h": "Harpa",
             "alt": "La facciata a nido d'ape di vetro dell'auditorium Harpa al crepuscolo",
             "p": "Un alveare di vetro costruito attraverso un crac che stava per farlo fuori"},
            {"href": "porto-vecchio-reykjavik", "img": "tile-old-harbour", "h": "Il porto vecchio",
             "alt": "Pescherecci ormeggiati nel porto vecchio di Reykjavik",
             "p": "Da qui partono le barche per le balene, e qui si sono vinte le Guerre del merluzzo"},
            {"href": "cosa-vedere-a-reykjavik", "img": "tile-whales", "h": "Whales of Iceland",
             "alt": "Balene a grandezza naturale illuminate di blu nella mostra Whales of Iceland",
             "p": "Ventitré balene a grandezza naturale in un capannone buio sull'acqua"},
            {"href": "cosa-vedere-a-reykjavik", "img": "tile-thufa", "h": "Þúfa",
             "alt": "Þúfa, la collinetta a spirale coperta d'erba con l'essiccatoio per il pesce in cima",
             "p": "La fine del percorso: una collina a spirale con sopra un essiccatoio per il pesce"}],
        "how_h2": "Come funziona l'audioguida",
        "steps": [{"h": "Compra", "p": "Un pagamento su questa pagina. La mail di attivazione arriva in pochi minuti."},
                  {"h": "Scarica", "p": "Installa l'app gratuita TouringBee, attiva l'acquisto e scarica il tour con il wi-fi dell'hotel."},
                  {"h": "Cammina", "p": "La mappa offline mostra dove sei. Arrivato a una tappa premi play: l'app non ti interrompe mai da sola."},
                  {"h": "Tienilo", "p": "Un anno di accesso. Torna d'inverno e rifai lo stesso giro al buio."}],
        "how_note": "Porta le cuffie. Il vento islandese copre l'altoparlante del telefono.",
        "basics_h2": "Reykjavik in pratica",
        "facts": [("Arrivare", "Keflavík (KEF), ~45 min con Flybus o in auto"),
                  ("Valuta", "Corona islandese (ISK): carta ovunque, contanti quasi mai"),
                  ("Muoversi", "A piedi in centro, bus Strætó, auto per le escursioni"),
                  ("Lingua", "Islandese; l'inglese si parla praticamente ovunque"),
                  ("Stagione aurore", "~settembre-aprile, solo notti buie e limpide"),
                  ("Sole di mezzanotte", "~maggio-luglio, quasi mai buio vero"),
                  ("Meteo", "Cambia ogni ora. Strati impermeabili, non l'ombrello"),
                  ("Acqua del rubinetto", "Ottima e gratis. Qui non comprare bottiglie")],
        "book_h3": "Prenota prima quello che si paga",
        "book_p": "Reykjavik raramente esaurisce, ma quello per cui la gente prende l'aereo sì: Blue Lagoon, Sky Lagoon, barche per l'aurora e Circolo d'Oro d'estate. Prenotare prima evita anche di dover rifare la passeggiata per colpa di una coda.",
        "book_cta": "Biglietti per Reykjavik su Tiqets",
        "partners_h2": "Escursioni e biglietti",
        "partners_lead": "La passeggiata copre la città. Tutto quello che segue sta fuori città, e sono le prenotazioni da chiudere prima di atterrare.",
        "p_golden_h": "Circolo d'Oro",
        "p_golden_p": "Tre tappe, una giornata lunga: il giro islandese classico, e il più affollato.",
        "p_blue_p": "Vicina all'aeroporto, quindi funziona come prima o ultima sosta. Gli slot si esauriscono.",
        "p_blue_alt": "La spa geotermale Blue Lagoon con il vapore sopra un'acqua azzurro latte",
        "p_aurora_h": "Aurora boreale",
        "p_aurora_p": "Barche e minibus che inseguono il cielo sgombro. Quasi tutti ti riprogrammano gratis se si copre.",
        "p_aurora_alt": "Aurora boreale verde sopra una strada fuori Reykjavik",
        "p_sky_p": "L'alternativa cittadina alla Blue Lagoon: più vicina, più economica da raggiungere, stesso vapore.",
        "p_sky_alt": "Una laguna geotermale illuminata di blu la sera vicino a Reykjavik",
        "car_h3": "Guidi tu? Prenota presto",
        "car_p": "Circolo d'Oro e costa sud si godono meglio al volante: ti fermi dove vuoi e non dipendi dall'orario del pullman. Il parco auto a noleggio islandese è piccolo e d'estate si esaurisce con settimane di anticipo. È una delle poche prenotazioni da chiudere davvero prima di partire.",
        "car_cta": "Confronta i noleggi",
        "car_link": ("circolo-doro-auto-o-tour", "Auto o tour?"),
        "cross_h2": "Altre passeggiate audio TouringBee",
        "cross_lead": "L'Islanda ha commerciato con Copenaghen per due secoli, e non per scelta. Il tour racconta quella storia; tanto vale sentire anche l'altra versione.",
        "cross": [{"h": "Copenaghen", "path": "product/copenhagen-city-tour",
                   "p": "La città che ha gestito l'economia islandese per duecento anni, a piedi in circa tre ore.",
                   "cta": "Copenhagen Walking Tour"},
                  {"h": "Oslo", "path": "product/oslo-city-tour",
                   "p": "Da lì è partito Ingólfur Arnarson, più o meno, e lì cominciano le saghe.",
                   "cta": "Oslo City Walking Tour"},
                  {"h": "Tutto il catalogo", "path": "shop-tbee",
                   "p": "Un centinaio di passeggiate audio in autonomia, in Europa e oltre.",
                   "cta": "Vai allo shop"}],
        "plan_h2": "Organizza la visita",
        "plan": [{"h": "Arrivare", "links": [("aeroporto-keflavik-reykjavik", "Aeroporto di Keflavík"), ("muoversi-a-reykjavik", "Muoversi in città")]},
                 {"h": "Escursioni", "links": [("circolo-doro", "Circolo d'Oro"), ("costa-sud-islanda", "Costa sud"), ("escursioni-da-reykjavik", "Tutte le escursioni")]},
                 {"h": "Quando", "links": [("quando-andare-a-reykjavik", "Quando andare"), ("cosa-mettere-in-valigia-islanda", "Cosa mettere in valigia"), ("aurora-boreale-reykjavik", "Aurora boreale")]},
                 {"h": "In città", "links": [("hallgrimskirkja", "Hallgrímskirkja"), ("perlan", "Perlan"), ("street-art-reykjavik", "Street art")]},
                 {"h": "Acqua", "links": [("blue-lagoon", "Blue Lagoon"), ("sky-lagoon", "Sky Lagoon"), ("piscine-geotermali-reykjavik", "Piscine cittadine")]},
                 {"h": "Pratico", "links": [("prezzi-reykjavik", "Quanto costa"), ("dove-dormire-a-reykjavik", "Dove dormire"), ("cucina-islandese", "Cosa mangiare")]}],
        "faq_h2": "Domande frequenti",
        "faq": [
            ("Quanti giorni servono a Reykjavik?", "Due giorni pieni bastano per la città: uno per la passeggiata e i musei, uno per una laguna o il porto. Aggiungi un giorno per ogni grande escursione — uno per il Circolo d'Oro, uno per la costa sud. Quasi tutti sottovalutano quanto tempo, in un viaggio in Islanda, si passa dentro un mezzo."),
            ("Il centro si gira a piedi?", "Del tutto. Le 27 tappe fanno circa 5 km quasi senza dislivello, a parte la salita di Skólavörðustígur verso la chiesa. Il limite è il meteo, non la distanza."),
            ("L'audioguida parte da sola mentre cammino?", "No, ed è voluto. La mappa offline mostra dove sei, ma il play lo premi tu quando arrivi alla tappa. La precisione del GPS di un telefono varia troppo perché l'avvio automatico sia affidabile. In manuale non perdi una storia solo perché il telefono ti credeva nella via accanto."),
            ("Serve la connessione dati durante la passeggiata?", "No. Scarichi il tour una volta in wi-fi e funziona tutto offline, mappa compresa."),
            ("Si vede l'aurora dalla città?", "Sì, in una notte buia e limpida tra settembre e aprile circa. Il faro di Grótta, a Seltjarnarnes, e il tratto scuro del lungomare di Sæbraut sono i posti soliti. L'inquinamento luminoso del centro gioca contro e le nuvole battono tutto: nessuna stagione e nessun tour può promettere un'aurora."),
            ("Reykjavik è cara?", "Mangiare fuori e gli alcolici sì, parecchio. La città in sé no: la passeggiata, il porto, i murales e i parchi sono gratis, l'acqua del rubinetto è ottima e le piscine geotermali costano una frazione della Blue Lagoon. Il budget se ne va in escursioni e cene."),
            ("Come ci si veste?", "Giacca impermeabile, strato caldo, scarpe che non scivolano e un berretto, in qualsiasi mese. L'ombrello è inutile: il vento di Reykjavik lo distrugge, e i locali se ne accorgono."),
            ("L'audioguida è in italiano?", "Il Reykjavík City Walking Tour per ora è narrato in inglese. Altri tour TouringBee sono disponibili in otto lingue."),
        ],
        "final_h2": "Cammina e ascolta perché",
        "final_p": "Ventisette tappe, due ore e mezza, e un pescatore di nome Y'Own che ti spiega perché niente di tutto questo è come sembra.",
        "final_cta2": "Vedi le escursioni",
    },

    "legal": {
        "privacy": '''<h2>Chi gestisce questo sito</h2>
<p>reykjavikwalk.com è pubblicato da Touringbee Limited, società registrata in Irlanda con il numero 660321. Scrivici a <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>
<h2>Cosa raccogliamo</h2>
<p>Non serve creare un account e su questo sito non raccogliamo nomi, indirizzi o dati di pagamento. Se acquisti l'audioguida, la cassa è gestita da Bókun e il pagamento da Stripe: i dati della tua carta li trattano loro, mai noi.</p>
<p>Come quasi ogni sito, il nostro hosting registra log standard: indirizzo IP, tipo di browser, pagina richiesta e orario. Servono al funzionamento e alla sicurezza.</p>
<h2>Analytics e cookie</h2>
<p>Usiamo analytics rispettosi della privacy per contare le visite e capire quali guide servono. Non vendiamo dati e non ospitiamo circuiti pubblicitari.</p>
<p>Quando segui un link di affiliazione verso partner come GetYourGuide, Tiqets o Booking.com, quel partner può impostare un cookie per attribuirci la prenotazione. Da quel momento vale la loro policy.</p>
<h2>L'audioguida</h2>
<p>Gli acquisti del Reykjavík City Walking Tour sono gestiti da Bókun (pagamento) e TouringBee (invio del link di attivazione). Le loro condizioni: <a href="https://touringbee.com/terms-and-conditions-of-use/" target="_blank" rel="noopener">touringbee.com/terms-and-conditions-of-use</a>.</p>
<h2>I tuoi diritti</h2>
<p>Nell'UE e nel Regno Unito puoi chiedere quali dati personali conserviamo, farli correggere o cancellare. Scrivi a <a href="mailto:info@touringbee.com">info@touringbee.com</a>: rispondiamo entro 30 giorni.</p>''',
        "affiliate": '''<p>Alcuni link di reykjavikwalk.com sono affiliati. Se prenoti o acquisti tramite loro, riceviamo una commissione. A te non costa nulla in più: il prezzo è lo stesso del diretto.</p>
<h2>Con chi lavoriamo</h2>
<ul class="ticks">
<li><strong>GetYourGuide</strong> — escursioni, tour per l'aurora, avvistamento balene, transfer</li>
<li><strong>Tiqets</strong> — biglietti per attrazioni e lagune</li>
<li><strong>Booking.com</strong> — hotel e noleggio auto</li>
</ul>
<h2>Il nostro prodotto</h2>
<p>L'audioguida Reykjavík City Walking Tour è fatta da TouringBee, che pubblica questo sito. Non siamo neutrali: pensiamo che sia il modo migliore per girare Reykjavik a piedi, e lo diciamo. Puoi comprarla qui o direttamente da TouringBee, allo stesso prezzo.</p>
<h2>Cosa cambia in quello che scriviamo</h2>
<p>La commissione non decide mai il contenuto di una guida. In più punti consigliamo le piscine geotermali al posto della Blue Lagoon, anche se la Blue Lagoon paga meglio, e diciamo quali attrazioni non valgono il prezzo. Una raccomandazione che esiste solo perché paga non è una raccomandazione.</p>
<p>Prezzi, orari e disponibilità cambiano. Verifica sempre sul sito dell'operatore prima di partire.</p>
<p>Domande: <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>''',
    },
}
