# -*- coding: utf-8 -*-
"""Português (PT-PT) — você. Sem «joia escondida», «imperdível», «de tirar o fôlego»."""

G = [
    ("P0", "circulo-dourado", "Círculo Dourado a partir de Reykjavik", "Þingvellir, Geysir e Gullfoss num dia: de carro ou em excursão."),
    ("P0", "blue-lagoon", "Blue Lagoon: bilhetes e transferes", "Como encaixá-la entre voos e se o preço se justifica."),
    ("P0", "auroras-boreais-reykjavik", "Auroras boreais em Reykjavik", "Época, previsão, pontos dentro da cidade e quando a excursão compensa."),
    ("P0", "hallgrimskirkja", "Hallgrímskirkja e a torre", "A igreja, o elevador, a fila e a melhor hora para subir."),
    ("P0", "aeroporto-keflavik-reykjavik", "Do aeroporto de Keflavík ao centro", "Flybus, transfer privado e carro alugado: preço e tempo comparados."),
    ("P0", "sky-lagoon", "Sky Lagoon", "O spa geotérmico às portas da cidade e o seu ritual de sete passos."),
    ("P0", "observacao-baleias-reykjavik", "Baleias e papagaios-do-mar", "Os barcos do porto velho, as épocas e o enjoo."),
    ("P0", "quando-ir-a-reykjavik", "Quando ir a Reykjavik", "Luz, auroras, tempo e preços, mês a mês."),
    ("P0", "um-dia-em-reykjavik", "Um dia em Reykjavik", "O percurso a pé que faz caber o essencial num só dia."),
    ("P0", "o-que-fazer-em-reykjavik", "O que fazer em Reykjavik", "A lista completa, ordenada pelo que merece as suas horas de luz."),
    ("P1", "circulo-dourado-carro-ou-excursao", "Círculo Dourado: carro ou excursão?", "Comparação honesta de custo e tempo."),
    ("P1", "excursoes-a-partir-de-reykjavik", "Excursões a partir de Reykjavik", "Todas as que valem a viagem, com tempos de estrada."),
    ("P1", "costa-sul-islandia", "A costa sul num dia", "Seljalandsfoss, Skógafoss e a praia negra de Reynisfjara."),
    ("P1", "sun-voyager", "O Sun Voyager e a marginal", "A escultura que toda a gente fotografa — e o que representa mesmo."),
    ("P1", "harpa", "Sala de concertos Harpa", "O favo de vidro, e como sobreviveu ao colapso."),
    ("P1", "porto-velho-reykjavik", "O porto velho", "Barcos, comida, o navio da guarda costeira e as Guerras do Bacalhau."),
    ("P1", "rua-arco-iris-laugavegur", "A rua arco-íris e a Laugavegur", "A rua pintada e a artéria comercial."),
    ("P1", "perlan", "Perlan", "A cúpula, a gruta de gelo e o miradouro."),
    ("P1", "dois-dias-em-reykjavik", "Dois dias em Reykjavik", "Um plano mais lento, com espaço para uma lagoa."),
    ("P1", "o-que-levar-para-a-islandia", "O que levar e como vestir", "As camadas que aguentam um tempo que muda de hora a hora."),
    ("P1", "como-circular-em-reykjavik", "Como circular em Reykjavik", "A pé, de autocarro Strætó, e quando precisa de carro."),
    ("P1", "precos-reykjavik", "Reykjavik é cara?", "Quanto custam as coisas de facto e onde poupar."),
    ("P1", "onde-ficar-em-reykjavik", "Onde ficar em Reykjavik", "Os bairros explicados e o que paga por cada um."),
    ("P2", "arte-urbana-reykjavik", "Arte urbana em Reykjavik", "Os murais, incluindo aquele vampiro que ninguém explica."),
    ("P2", "farol-de-grotta", "Grótta e os melhores sítios para auroras", "Onde se colocar quando o céu fica verde."),
    ("P2", "tjornin-austurvollur-parlamento", "Tjörnin, Austurvöllur e o Alþingi", "O lago, a praça e o parlamento mais antigo do mundo."),
    ("P2", "comida-islandesa", "Comida islandesa", "Pylsa, skyr, sopa de borrego, hákarl: o que provar e o que deixar."),
    ("P2", "piscinas-geotermicas-reykjavik", "Piscinas geotérmicas e as suas regras", "As regras do duche de que ninguém avisa os turistas."),
    ("P2", "reykjavik-de-graca", "Reykjavik de graça", "Um dia inteiro que não custa nada."),
    ("P2", "museus-reykjavik", "Museus de Reykjavik", "O Museu Nacional, a exposição 871±2 e os mais estranhos."),
]

CONTENT = {
    "slugs": {"guides": "guias", "privacy": "politica-de-privacidade",
              "affiliate": "aviso-de-afiliacao"},
    "guides": [{"wave": w, "slug": s, "title": t, "desc": d} for w, s, t, d in G],

    "ui": {
        "menu": "Guias", "menu_all": "Todos os guias",
        "buy": "Comprar o audioguia — 9,99 €",
        "see_tours": "Ver excursões", "check_tickets": "Ver bilhetes",
        "sticky_title": "Reykjavík City Walking Tour — 9,99 €",
        "sticky_sub": "4,7 ★ · 27 paragens · offline · em inglês",
        "sticky_btn": "Comprar",
        "rating_aria": "Classificado com 4,7 em 5",
        "rating_label": "classificação média dos viajantes",
        "price_display": "9,99 €",
        "price_sub": "Pagamento único · sem subscrição · acesso 1 ano",
        "checkout_note": "Pagamento seguro nesta página. Prefere a loja?",
        "open_shop": "Abrir na TouringBee",
        "audio_fallback": "O seu navegador não reproduz áudio.",
        "product_name": "Reykjavík City Walking Tour",
        "product_name_full": "Reykjavík City Walking Tour — audioguia autoguiado",
        "product_desc": "Um percurso a pé autoguiado por Reykjavik com 27 paragens, áudio e mapa GPS offline, do monumento a Ingólfur Arnarson até Þúfa. Cerca de 2 a 2,5 horas.",
        "product_category": "Audioguia autoguiado",
        "author_h": "Sobre o autor",
        "author_alt": "Eugene, autor dos audioguias TouringBee",
        "author_bio": "Eugene vive em França há dezasseis anos, trabalhou como guia e fundou a rede de conteúdos de viagem paris10.travel. Visitou mais de 300 cidades e aldeias francesas e escreve os audioguias TouringBee. Constrói estes guias como quem prepara um amigo antes da viagem: o que vale mesmo o seu tempo, o que reservar e o que pode saltar.",
        "author_bio_plain": "Antigo guia, fundador da paris10.travel, autor dos audioguias TouringBee.",
        "f_explore": "Explorar", "f_product": "O audioguia", "f_legal": "Legal",
        "f_langs": "Idiomas", "f_alltours": "Todos os audioguias TouringBee",
        "f_terms": "Termos e condições",
        "langnames": {"en": "English", "fr": "Français", "de": "Deutsch", "es": "Español",
                      "it": "Italiano", "pt": "Português", "pl": "Polski", "ru": "Русский"},
        "disclaimer": "reykjavikwalk.com é publicado pela Touringbee Limited (Irlanda, sociedade n.º 660321). Alguns links deste site são de afiliação: se reservar através deles, recebemos uma comissão, sem custo adicional para si. Preços e horários mudam; confirme sempre no site oficial antes de viajar.",
        "guides_h1": "Todos os guias de Reykjavik",
        "guides_title": "Todos os guias de Reykjavik | TouringBee",
        "guides_meta": "Todos os guias de reykjavikwalk.com: Círculo Dourado, Blue Lagoon, auroras boreais, Hallgrímskirkja, transferes do aeroporto, roteiros e mais.",
        "guides_lead": 'Trinta guias sobre Reykjavik e as excursões que partem de lá, publicados por vagas. Comece pelo <a href="/pt/">guia completo de Reykjavik</a> — tudo o que se segue aprofunda uma peça.',
        "in_production": "Em preparação",
        "waves": {"P0": "Primeira vaga — em escrita",
                  "P1": "Segunda vaga", "P2": "Terceira vaga"},
        "updated": "Última atualização: 6 de agosto de 2026",
        "privacy_title": "Política de privacidade",
        "privacy_meta": "Como o reykjavikwalk.com trata dados, cookies e rastreio de afiliação.",
        "affiliate_title": "Aviso de afiliação",
        "affiliate_meta": "Que links do reykjavikwalk.com são de afiliação, com quem trabalhamos e o que isso muda nas nossas recomendações.",
        "nf_h1": "Esta página não existe",
        "nf_p": "Ou ainda não foi publicada, ou o link está errado. Ambas as coisas se resolvem.",
        "nf_cta1": "Guia completo de Reykjavik",
    },

    "home": {
        "city": "Reykjavik",
        "city_desc": "A capital da Islândia e a capital mais a norte do mundo.",
        "title": "O que fazer em Reykjavik: percurso a pé e excursões | TouringBee",
        "meta": "Prepare Reykjavik a sério: um percurso a pé autoguiado de 27 paragens com áudio offline, mais o Círculo Dourado, a Blue Lagoon, as auroras boreais e tudo o que a capital mais setentrional do mundo faz melhor.",
        "hero_alt": "A escultura Sun Voyager na marginal de Reykjavik sob um céu islandês enorme",
        "chip": "27 paragens · 2 a 2,5 horas · funciona offline",
        "h1": "Reykjavik a pé, ao seu ritmo",
        "sub": "A capital mais a norte do mundo faz-se numa tarde a pé — desde que saiba o que está a ver. Este é o guia completo: o percurso, as excursões que compensa reservar e as estações, que mudam tudo.",
        "cta_inside": "Ver o que inclui", "cta_preview": "Ouvir um excerto",
        "cta_daytrips": "Excursões",
        "intro1": "Reykjavik é pequena. Cerca de 140.000 habitantes, um centro antigo que se atravessa em vinte minutos e quase tudo aquilo que o trouxe cá está nesse percurso. O resto fica a vinte minutos de autocarro.",
        "intro2": "É aí que está a armadilha. Parece uma cidade que se «despacha» numa manhã. Por isso fotografa-se a igreja, fotografa-se o Sun Voyager e vai-se embora. Sem nunca ter ouvido como um povo de pescadores venceu a Royal Navy. Nem porque é que em 2013 desviaram uma estrada já traçada: os vizinhos tinham saído em defesa dos elfos.",
        "intro3": 'As histórias é que interessam. Foi por isso que fizemos o <a href="#audio">Reykjavík City Walking Tour</a>: 27 paragens, da estátua do fundador da cidade até um montículo de erva junto ao porto, com um secadouro de peixe em cima. Carregue no play, caminhe e pare onde quiser. Duas horas e meia. Ou uma tarde inteira, se continuar a parar para um café. E vai parar.',
        "preview_h": "Ouça o início",
        "preview_p": "30 segundos da introdução, em inglês",
        "highlights": [("O percurso", "De Arnarhóll a Þúfa, 27 paragens numeradas"),
                       ("Funciona em", "iPhone e Android, totalmente offline"),
                       ("O ritmo", "O seu: pausa, desvio, continua"),
                       ("Acesso", "Um pagamento, um ano")],
        "prod_h2": "O Reykjavík City Walking Tour",
        "prod_lead": "Escrito por jornalistas e historiadores, narrado por Y'Own — um pescador de Reykjavik com tempo livre antes de voltar ao mar.",
        "prod_alt": "A aplicação TouringBee com o percurso de Reykjavik, segurada diante da Hallgrímskirkja",
        "ticks": ["<strong>27 paragens áudio</strong>: Hallgrímskirkja, o Sun Voyager, a Harpa, o museu do punk, o ICGV Óðinn, Þúfa e mais",
                  "<strong>Mapa GPS offline</strong> mostra onde está; a gravação é você que a inicia ao chegar ao ponto",
                  "<strong>Ilustrações</strong> para saber que edifício tem à frente",
                  "<strong>Entrega imediata</strong>: o email de ativação chega em poucos minutos",
                  "<strong>Sem grupo nem horário</strong>: começa no dia e à hora que quiser"],
        "why_h2": "Porque é que Reykjavik merece mais do que uma escala",
        "why_p1": "Há mil anos, um norueguês chamado Ingólfur Arnarson atirou ao mar os esteios lavrados do seu assento de honra e deixou os deuses escolherem onde iria viver. Os seus escravos levaram três anos a encontrá-los, dados à costa numa baía cheia de vapor. Chamou-lhe <em>Reykjavík</em>, baía fumegante. Esse vapor continua a ser a razão de a água do seu duche cheirar a enxofre.",
        "why_p2": "Durante os mil anos seguintes, a Islândia foi governada por outros. A Noruega, depois a Dinamarca, depois um monopólio comercial dirigido a partir de Copenhaga, que estrangulou a economia durante dois séculos. A independência chegou por fases e só se completou em 1944. Isso cabe na memória de uma só geração, e nota-se: este é um país que ainda se espanta um pouco por se governar sozinho.",
        "why_img1_alt": "O edifício do governo em Reykjavik com uma estátua em frente",
        "why_img2_alt": "Uma visitante passa junto ao Sun Voyager na marginal de Sæbraut, no inverno",
        "light_h3": "Aqui quem manda é a luz",
        "light_p1": "Nada condiciona uma visita a Reykjavik como o céu. Entre maio e julho o sol quase não se dá ao trabalho de se pôr e a cidade fica acordada com ele. Em novembro e dezembro tem quatro ou cinco horas de luz aproveitável, e tudo o que planeou tem de caber aí.",
        "light_p2": "Em troca, há as auroras. Grosso modo de setembro a abril, numa noite escura e limpa, vêem-se de dentro da cidade: o farol de Grótta e a marginal de Sæbraut são os sítios do costume. Nem a época nem uma excursão garantem nada. Um céu limpo garante.",
        "light_link": ("quando-ir-a-reykjavik", "Quando vir"),
        "free_h3": "Quase tudo é gratuito",
        "free_p": "O percurso não custa nada. O centro de Reykjavik é um museu ao ar livre: os murais, o porto, o lago, o parlamento, a rua arco-íris. O que se paga conta-se pelos dedos de uma mão: o elevador da torre da Hallgrímskirkja, o Perlan, os museus e as piscinas geotérmicas — algumas centenas de coroas, e bem gastas. Guarde o orçamento para as excursões. É aí que a Islândia fica cara.",
        "free_link": ("precos-reykjavik", "Quanto custa mesmo Reykjavik"),
        "weird_h3": "Uma cidade que não tem vergonha de ser estranha",
        "weird_p1": "Reykjavik tem um museu do falo, um museu do punk instalado numas antigas casas de banho públicas, um mural com um vampiro e uma locomotiva a vapor que nunca teve via por onde andar. Durante dezassete anos a televisão parava em julho para as pessoas saírem de casa. E uma vez a cidade derrubou um governo à panelada.",
        "weird_p2": "Nos postais não aparece nada disto. No percurso está tudo.",
        "weird_img_alt": "A locomotiva a vapor preservada junto ao porto velho de Reykjavik",
        "oneday_link": ("um-dia-em-reykjavik", "Ver o plano de um dia"),
        "tiles_h2": "O que vai ver pelo caminho",
        "tiles_lead": "Seis das vinte e sete paragens. As restantes encontra-as a caminhar.",
        "tiles": [
            {"href": "hallgrimskirkja", "img": "tile-hallgrimskirkja", "h": "Hallgrímskirkja",
             "alt": "A igreja Hallgrímskirkja vista de baixo com a bandeira islandesa ao vento",
             "p": "A igreja de colunas de basalto e, da torre, a melhor vista da cidade"},
            {"href": "rua-arco-iris-laugavegur", "img": "tile-rainbow-street", "h": "A rua arco-íris",
             "alt": "Skólavörðustígur, a rua pintada de arco-íris que sobe até à Hallgrímskirkja",
             "p": "Skólavörðustígur, pintada para o Orgulho e nunca mais apagada"},
            {"href": "harpa", "img": "tile-harpa", "h": "Harpa",
             "alt": "A fachada em favo de vidro da sala Harpa ao anoitecer",
             "p": "Um favo de vidro erguido no meio de um colapso que quase o levou"},
            {"href": "porto-velho-reykjavik", "img": "tile-old-harbour", "h": "O porto velho",
             "alt": "Barcos de pesca atracados no porto velho de Reykjavik",
             "p": "Daqui saem os barcos das baleias — e aqui se ganharam as Guerras do Bacalhau"},
            {"href": "o-que-fazer-em-reykjavik", "img": "tile-whales", "h": "Whales of Iceland",
             "alt": "Baleias em tamanho real iluminadas a azul na exposição Whales of Iceland",
             "p": "Vinte e três baleias em tamanho real num pavilhão escuro junto à água"},
            {"href": "o-que-fazer-em-reykjavik", "img": "tile-thufa", "h": "Þúfa",
             "alt": "Þúfa, o montículo em espiral coberto de erva com o secadouro de peixe no topo",
             "p": "O fim do percurso: uma colina em espiral com um secadouro de peixe em cima"}],
        "how_h2": "Como funciona o audioguia",
        "steps": [{"h": "Compre", "p": "Um pagamento nesta página. O email de ativação chega em poucos minutos."},
                  {"h": "Descarregue", "p": "Instale a app gratuita TouringBee, ative a compra e descarregue o percurso com o wi-fi do hotel."},
                  {"h": "Caminhe", "p": "O mapa offline mostra onde está. Ao chegar a uma paragem, carregue no play: a app nunca o interrompe sozinha."},
                  {"h": "Fique com ele", "p": "Um ano de acesso. Volte no inverno e faça o mesmo percurso às escuras."}],
        "how_note": "Leve auscultadores. O vento islandês é mais alto do que o altifalante do telemóvel.",
        "basics_h2": "Reykjavik na prática",
        "facts": [("Chegar", "Keflavík (KEF), ~45 min de Flybus ou de carro"),
                  ("Moeda", "Coroa islandesa (ISK): cartão em todo o lado, dinheiro quase nunca"),
                  ("Circular", "A pé no centro, autocarros Strætó, carro para as excursões"),
                  ("Língua", "Islandês; fala-se inglês praticamente em todo o lado"),
                  ("Época de auroras", "~setembro a abril, só em noites escuras e limpas"),
                  ("Sol da meia-noite", "~maio a julho, quase sem escuridão a sério"),
                  ("Tempo", "Muda de hora a hora. Camadas impermeáveis batem o guarda-chuva"),
                  ("Água da torneira", "Excelente e grátis. Nunca compre engarrafada aqui")],
        "book_h3": "Reserve antes o que se paga",
        "book_p": "Reykjavik raramente esgota. Aquilo por que as pessoas apanham o avião, esse sim: Blue Lagoon, Sky Lagoon, barcos das auroras e o Círculo Dourado no verão. Reservar antes evita também ter de refazer o passeio por causa de uma fila.",
        "book_cta": "Bilhetes para Reykjavik na Tiqets",
        "partners_h2": "Excursões e bilhetes",
        "partners_lead": "O percurso cobre a cidade. Tudo o que se segue fica fora dela — e são estas as reservas a fechar antes de aterrar.",
        "p_golden_h": "Círculo Dourado",
        "p_golden_p": "Três pontos, um dia longo: o circuito islandês clássico, e o mais concorrido.",
        "p_blue_p": "Perto do aeroporto, por isso funciona como primeira ou última paragem. Os horários esgotam.",
        "p_blue_alt": "O spa geotérmico Blue Lagoon com vapor sobre água azul leitosa",
        "p_aurora_h": "Auroras boreais",
        "p_aurora_p": "Barcos e minibus que perseguem o céu limpo. A maioria remarca sem custo se o tempo fechar.",
        "p_aurora_alt": "Auroras boreais verdes sobre uma estrada nos arredores de Reykjavik",
        "p_sky_p": "A alternativa junto à cidade à Blue Lagoon: mais perto, mais barata de alcançar, o mesmo vapor.",
        "p_sky_alt": "Uma lagoa geotérmica iluminada a azul ao anoitecer perto de Reykjavik",
        "car_h3": "Vai conduzir? Reserve cedo",
        "car_p": "O Círculo Dourado e a costa sul sabem melhor ao volante: pode parar onde quiser e escapa ao horário do autocarro. A frota de aluguer islandesa é pequena e no verão esgota com semanas de antecedência. É uma das poucas reservas que compensa mesmo fechar antes de voar.",
        "car_cta": "Comparar carros de aluguer",
        "car_link": ("circulo-dourado-carro-ou-excursao", "Carro ou excursão?"),
        "cross_h2": "Outros percursos áudio da TouringBee",
        "cross_lead": "A Islândia comerciou com Copenhaga durante dois séculos — e não por vontade própria. O percurso conta essa história; já agora, ouça o outro lado.",
        "cross": [{"h": "Copenhaga", "path": "product/copenhagen-city-tour",
                   "p": "A cidade que geriu a economia islandesa durante duzentos anos, a pé em cerca de três horas.",
                   "cta": "Copenhagen Walking Tour"},
                  {"h": "Oslo", "path": "product/oslo-city-tour",
                   "p": "De lá partiu Ingólfur Arnarson, mais ou menos — e é aí que começam as sagas.",
                   "cta": "Oslo City Walking Tour"},
                  {"h": "Todo o catálogo", "path": "shop-tbee",
                   "p": "Cerca de cem percursos áudio autoguiados, na Europa e fora dela.",
                   "cta": "Ver a loja"}],
        "plan_h2": "Preparar a visita",
        "plan": [{"h": "Chegar", "links": [("aeroporto-keflavik-reykjavik", "Aeroporto de Keflavík"), ("como-circular-em-reykjavik", "Circular na cidade")]},
                 {"h": "Excursões", "links": [("circulo-dourado", "Círculo Dourado"), ("costa-sul-islandia", "Costa sul"), ("excursoes-a-partir-de-reykjavik", "Todas as excursões")]},
                 {"h": "Quando", "links": [("quando-ir-a-reykjavik", "Quando ir"), ("o-que-levar-para-a-islandia", "O que levar"), ("auroras-boreais-reykjavik", "Auroras boreais")]},
                 {"h": "Na cidade", "links": [("hallgrimskirkja", "Hallgrímskirkja"), ("perlan", "Perlan"), ("arte-urbana-reykjavik", "Arte urbana")]},
                 {"h": "Água", "links": [("blue-lagoon", "Blue Lagoon"), ("sky-lagoon", "Sky Lagoon"), ("piscinas-geotermicas-reykjavik", "Piscinas da cidade")]},
                 {"h": "Prático", "links": [("precos-reykjavik", "Quanto custa"), ("onde-ficar-em-reykjavik", "Onde ficar"), ("comida-islandesa", "O que comer")]}],
        "faq_h2": "Perguntas frequentes",
        "faq": [
            ("Quantos dias são precisos em Reykjavik?", "Dois dias inteiros cobrem a cidade com folga: um para o percurso e os museus, outro para uma lagoa ou o porto. Some um dia por cada grande excursão — um para o Círculo Dourado, outro para a costa sul. Quase toda a gente subestima o tempo que uma viagem à Islândia passa dentro de um veículo."),
            ("O centro faz-se a pé?", "Inteiramente. As 27 paragens dão cerca de 5 km quase sem desnível, tirando a subida da Skólavörðustígur até à igreja. O limite é o tempo, não a distância."),
            ("O audioguia arranca sozinho enquanto caminho?", "Não, e é de propósito. O mapa offline mostra onde está, mas é você que carrega no play ao chegar à paragem. A precisão do GPS de um telemóvel varia demasiado para o disparo automático ser fiável. Em manual, não perde uma história só porque o telefone o julgava na rua ao lado."),
            ("Preciso de dados móveis durante o percurso?", "Não. Descarregue o percurso uma vez em wi-fi e funciona tudo offline, mapa incluído."),
            ("Vêem-se as auroras de dentro de Reykjavik?", "Vêem-se, numa noite escura e limpa entre setembro e abril, sensivelmente. O farol de Grótta, em Seltjarnarnes, e o troço escuro da marginal de Sæbraut são os sítios habituais. A luz do centro joga contra si e as nuvens ganham a tudo: nenhuma época nem excursão pode prometer uma aurora."),
            ("Reykjavik é cara?", "Comer fora e o álcool, sim, bastante. A cidade em si não: o percurso, o porto, os murais e os parques são gratuitos, a água da torneira é excelente e as piscinas geotérmicas custam uma fração da Blue Lagoon. O orçamento vai-se em excursões e jantares."),
            ("Como me devo vestir?", "Casaco impermeável, camada quente, calçado que não escorregue e um gorro, em qualquer mês. O guarda-chuva não serve: o vento de Reykjavik destrói-o, e os locais reparam."),
            ("O audioguia existe em português?", "O Reykjavík City Walking Tour é para já narrado em inglês. Outros percursos TouringBee estão disponíveis em oito idiomas."),
        ],
        "final_h2": "Caminhe e ouça porquê",
        "final_p": "Vinte e sete paragens, duas horas e meia, e um pescador chamado Y'Own a explicar-lhe porque é que nada disto é o que parece.",
        "final_cta2": "Ver excursões",
    },

    "legal": {
        "privacy": '''<h2>Quem edita este site</h2>
<p>O reykjavikwalk.com é publicado pela Touringbee Limited, sociedade registada na República da Irlanda com o número 660321. Escreva-nos para <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>
<h2>O que recolhemos</h2>
<p>Não é preciso criar conta e neste site não recolhemos nomes, moradas nem dados de pagamento. Se comprar o audioguia, a caixa é operada pela Bókun e o pagamento processado pela Stripe: os dados do seu cartão são tratados por eles, nunca por nós.</p>
<p>Como quase todos os sites, o nosso alojamento regista logs de servidor padrão: endereço IP, tipo de navegador, página pedida e hora. Servem para manter o site a funcionar e seguro.</p>
<h2>Estatísticas e cookies</h2>
<p>Usamos estatísticas respeitadoras da privacidade para contar visitas e perceber que guias são úteis. Não vendemos dados nem alojamos redes de publicidade.</p>
<p>Quando segue um link de afiliação para um parceiro como a GetYourGuide, a Tiqets ou a Booking.com, esse parceiro pode colocar um cookie para nos atribuir a reserva. A partir daí aplica-se a política deles.</p>
<h2>O audioguia</h2>
<p>As compras do Reykjavík City Walking Tour são geridas pela Bókun (pagamento) e pela TouringBee (envio do link de ativação). Condições: <a href="https://touringbee.com/terms-and-conditions-of-use/" target="_blank" rel="noopener">touringbee.com/terms-and-conditions-of-use</a>.</p>
<h2>Os seus direitos</h2>
<p>Na UE e no Reino Unido pode pedir que dados pessoais guardamos, corrigi-los ou apagá-los. Escreva para <a href="mailto:info@touringbee.com">info@touringbee.com</a> e respondemos em 30 dias.</p>''',
        "affiliate": '''<p>Alguns links do reykjavikwalk.com são de afiliação. Se reservar ou comprar através deles, recebemos uma comissão. A si não custa mais nada: o preço é o mesmo que ir diretamente.</p>
<h2>Com quem trabalhamos</h2>
<ul class="ticks">
<li><strong>GetYourGuide</strong> — excursões, auroras boreais, observação de baleias, transferes</li>
<li><strong>Tiqets</strong> — bilhetes de atrações e lagoas</li>
<li><strong>Booking.com</strong> — hotéis e aluguer de carros</li>
</ul>
<h2>O nosso produto</h2>
<p>O audioguia Reykjavík City Walking Tour é feito pela TouringBee, que publica este site. Não somos neutros: achamos que é a melhor forma de percorrer Reykjavik a pé, e dizemo-lo. Pode comprá-lo aqui ou diretamente na TouringBee, pelo mesmo preço.</p>
<h2>O que isso muda no que escrevemos</h2>
<p>A comissão nunca decide o conteúdo de um guia. Recomendamos várias vezes as piscinas geotérmicas em vez da Blue Lagoon, apesar de a Blue Lagoon pagar melhor, e dizemos que atrações não valem o dinheiro. Uma recomendação que só existe porque paga não é uma recomendação.</p>
<p>Preços, horários e disponibilidade mudam. Confirme sempre no site do operador antes de viajar.</p>
<p>Questões: <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>''',
    },
}
