# -*- coding: utf-8 -*-
"""Français — vous. Pas de « incontournable », « pépite », « à couper le souffle »."""

G = [
    ("P0", "cercle-dor", "Le Cercle d'Or depuis Reykjavik", "Þingvellir, Geysir et Gullfoss en une journée — au volant ou en excursion."),
    ("P0", "blue-lagoon", "Blue Lagoon : billets et navettes", "Comment le caler entre deux vols, et si le prix se justifie."),
    ("P0", "aurores-boreales-reykjavik", "Aurores boréales à Reykjavik", "La saison, la météo, les spots en ville, et quand l'excursion sert vraiment."),
    ("P0", "hallgrimskirkja", "Hallgrímskirkja et sa tour", "L'église, l'ascenseur, la file, et l'heure où monter."),
    ("P0", "aeroport-keflavik-reykjavik", "De l'aéroport de Keflavík au centre", "Flybus, transfert privé, voiture : prix et durée comparés."),
    ("P0", "sky-lagoon", "Sky Lagoon", "Le spa géothermal aux portes de la ville et son rituel en sept étapes."),
    ("P0", "observation-baleines-reykjavik", "Baleines et macareux", "Les bateaux du vieux port, les saisons, et le mal de mer."),
    ("P0", "quand-partir-reykjavik", "Quand partir à Reykjavik", "Lumière, aurores, météo et prix, mois par mois."),
    ("P0", "un-jour-a-reykjavik", "Un jour à Reykjavik", "L'itinéraire à pied qui fait tenir l'essentiel en une journée."),
    ("P0", "que-voir-a-reykjavik", "Que voir à Reykjavik", "La liste complète, classée selon ce qui mérite vos heures de jour."),
    ("P1", "cercle-dor-voiture-ou-excursion", "Cercle d'Or : voiture ou excursion ?", "Comparatif honnête, prix et temps à l'appui."),
    ("P1", "excursions-depuis-reykjavik", "Excursions depuis Reykjavik", "Toutes celles qui valent le déplacement, temps de route inclus."),
    ("P1", "cote-sud-islande", "La côte sud en une journée", "Seljalandsfoss, Skógafoss et la plage noire de Reynisfjara."),
    ("P1", "sun-voyager", "Le Sun Voyager et le front de mer", "La sculpture que tout le monde photographie — et ce qu'elle représente vraiment."),
    ("P1", "harpa", "Harpa, la salle de concert", "La ruche de verre, et comment elle a survécu au krach."),
    ("P1", "vieux-port-reykjavik", "Le vieux port", "Bateaux, restos, le garde-côtes, et les guerres de la morue."),
    ("P1", "rue-arc-en-ciel-laugavegur", "La rue arc-en-ciel et Laugavegur", "La rue peinte et l'artère commerçante."),
    ("P1", "perlan", "Perlan", "Le dôme, la grotte de glace et la terrasse panoramique."),
    ("P1", "deux-jours-a-reykjavik", "Deux jours à Reykjavik", "Un plan plus lent, avec un bain géothermal dedans."),
    ("P1", "quoi-emporter-islande", "Quoi emporter, comment s'habiller", "Les couches qui tiennent quand le temps change toutes les heures."),
    ("P1", "se-deplacer-a-reykjavik", "Se déplacer à Reykjavik", "À pied, en bus Strætó, et quand la voiture devient utile."),
    ("P1", "budget-reykjavik", "Reykjavik est-elle chère ?", "Ce que coûtent vraiment les choses, et où économiser."),
    ("P1", "ou-loger-a-reykjavik", "Où loger à Reykjavik", "Les quartiers expliqués, et ce que vous payez pour chacun."),
    ("P2", "street-art-reykjavik", "Le street art de Reykjavik", "Les fresques, dont ce vampire que personne n'explique."),
    ("P2", "phare-de-grotta", "Grótta et les meilleurs spots à aurores", "Où se poster quand le ciel devient vert."),
    ("P2", "tjornin-austurvollur-parlement", "Tjörnin, Austurvöllur et l'Alþingi", "L'étang, la place et le plus vieux parlement du monde."),
    ("P2", "cuisine-islandaise", "La cuisine islandaise", "Pylsa, skyr, soupe d'agneau, hákarl : ce qu'on goûte, ce qu'on évite."),
    ("P2", "piscines-geothermales-reykjavik", "Piscines géothermales et savoir-vivre", "Les règles de douche dont personne ne prévient les touristes."),
    ("P2", "reykjavik-gratuit", "Reykjavik gratuitement", "Une journée entière qui ne coûte rien."),
    ("P2", "musees-reykjavik", "Les musées de Reykjavik", "Le Musée national, l'expo 871±2, et les plus étranges."),
]

CONTENT = {
    "slugs": {"guides": "guides", "privacy": "politique-de-confidentialite",
              "affiliate": "divulgation-affiliation"},
    "guides": [{"wave": w, "slug": s, "title": t, "desc": d} for w, s, t, d in G],

    "ui": {
        "menu": "Guides", "menu_all": "Tous les guides",
        "buy": "Acheter l'audioguide — 9,99 €",
        "see_tours": "Voir les excursions", "check_tickets": "Voir les billets",
        "sticky_title": "Reykjavík City Walking Tour — 9,99 €",
        "sticky_sub": "4,7 ★ · 27 étapes · hors ligne · en anglais",
        "sticky_btn": "Acheter",
        "rating_aria": "Noté 4,7 sur 5",
        "rating_label": "note moyenne des voyageurs",
        "price_display": "9,99 €",
        "price_sub": "Paiement unique · sans abonnement · accès 1 an",
        "checkout_note": "Paiement sécurisé sur cette page. Vous préférez la boutique ?",
        "open_shop": "Ouvrir sur TouringBee",
        "audio_fallback": "Votre navigateur ne lit pas l'audio.",
        "product_name": "Reykjavík City Walking Tour",
        "product_name_full": "Reykjavík City Walking Tour — audioguide en autonomie",
        "product_desc": "Une visite à pied en autonomie de Reykjavík en 27 étapes, avec audio et carte GPS hors ligne, du monument d'Ingólfur Arnarson jusqu'à Þúfa. Environ 2 h à 2 h 30.",
        "product_category": "Audioguide en autonomie",
        "author_h": "À propos de l'auteur",
        "author_alt": "Eugene, auteur des audioguides TouringBee",
        "author_bio": "Eugene vit en France depuis seize ans. Ancien guide, il a fondé le réseau de contenus voyage paris10.travel, visité plus de 300 villes et villages français, et écrit les audioguides TouringBee. Il conçoit ces guides comme un briefing à un ami avant le départ : ce qui vaut vraiment votre temps, ce qu'il faut réserver, ce qu'on peut sauter.",
        "author_bio_plain": "Ancien guide, fondateur de paris10.travel, auteur des audioguides TouringBee.",
        "f_explore": "Explorer", "f_product": "L'audioguide", "f_legal": "Mentions légales",
        "f_langs": "Langues", "f_alltours": "Tous les audioguides TouringBee",
        "f_terms": "Conditions générales",
        "langnames": {"en": "English", "fr": "Français", "de": "Deutsch", "es": "Español",
                      "it": "Italiano", "pt": "Português", "pl": "Polski", "ru": "Русский"},
        "disclaimer": "reykjavikwalk.com est publié par Touringbee Limited (Irlande, société n° 660321). Certains liens de ce site sont des liens affiliés : si vous réservez via eux, nous touchons une commission, sans surcoût pour vous. Les prix et les horaires changent — vérifiez toujours sur le site officiel avant de partir.",
        "guides_h1": "Tous les guides Reykjavik",
        "guides_title": "Tous les guides Reykjavik | TouringBee",
        "guides_meta": "Tous les guides de reykjavikwalk.com : Cercle d'Or, Blue Lagoon, aurores boréales, Hallgrímskirkja, transferts aéroport, itinéraires et plus.",
        "guides_lead": 'Trente guides sur Reykjavik et les excursions qu\'on en fait, publiés par vagues. Commencez par le <a href="/fr/">guide complet de Reykjavik</a> — tout ce qui suit creuse un point précis.',
        "in_production": "En préparation",
        "waves": {"P0": "Première vague — en cours d'écriture",
                  "P1": "Deuxième vague", "P2": "Troisième vague"},
        "updated": "Dernière mise à jour : 6 août 2026",
        "privacy_title": "Politique de confidentialité",
        "privacy_meta": "Comment reykjavikwalk.com traite les données, les cookies et le suivi d'affiliation.",
        "affiliate_title": "Divulgation d'affiliation",
        "affiliate_meta": "Quels liens de reykjavikwalk.com sont affiliés, avec qui nous travaillons, et ce que cela change à nos recommandations.",
        "nf_h1": "Cette page n'existe pas",
        "nf_p": "Soit elle n'est pas encore publiée, soit le lien est faux. Les deux se réparent.",
        "nf_cta1": "Guide complet de Reykjavik",
    },

    "home": {
        "city": "Reykjavik",
        "city_desc": "La capitale de l'Islande, et la capitale la plus au nord du monde.",
        "title": "Que voir à Reykjavik : visite à pied et excursions | TouringBee",
        "meta": "Préparer Reykjavik pour de vrai : une visite à pied en 27 étapes avec audio hors ligne, plus le Cercle d'Or, le Blue Lagoon, les aurores boréales et tout ce que fait de mieux la capitale la plus septentrionale du monde.",
        "hero_alt": "La sculpture Sun Voyager sur le front de mer de Reykjavik, sous un grand ciel islandais",
        "chip": "27 étapes · 2 h à 2 h 30 · fonctionne hors ligne",
        "h1": "Reykjavik à pied, à votre rythme",
        "sub": "La capitale la plus au nord du monde tient dans un après-midi de marche — à condition de savoir ce que vous regardez. Voici le guide complet : le parcours, les excursions qui valent une réservation, et les saisons, qui changent tout.",
        "cta_inside": "Voir le contenu", "cta_preview": "Écouter un extrait",
        "cta_daytrips": "Excursions",
        "intro1": "Reykjavik est petite. Environ 140 000 habitants, un centre ancien qu'on traverse en vingt minutes, et presque tout ce que vous êtes venu voir se trouve sur ce trajet. Le reste est à vingt minutes de bus.",
        "intro2": "C'est le piège. La ville a l'air de se « faire » en une matinée. Alors on photographie l'église, on photographie le Sun Voyager, et on repart. Sans avoir appris comment un peuple de pêcheurs a battu la Royal Navy. Ni pourquoi, en 2013, une route déjà tracée a été déplacée : les riverains avaient pris la défense des elfes.",
        "intro3": 'Ce sont les histoires qui comptent. D\'où le <a href="#audio">Reykjavík City Walking Tour</a> : 27 étapes, de la statue du fondateur de la ville à une butte d\'herbe près du port, coiffée d\'un séchoir à poisson. Vous appuyez sur lecture, vous marchez, vous vous arrêtez où bon vous semble. Deux heures et demie. Ou tout un après-midi, si vous cédez à un café en chemin. Et vous céderez.',
        "preview_h": "Écoutez l'introduction",
        "preview_p": "30 secondes du début, en anglais",
        "highlights": [("Le parcours", "D'Arnarhóll à Þúfa, 27 étapes numérotées"),
                       ("Fonctionne sur", "iPhone et Android, entièrement hors ligne"),
                       ("Le rythme", "Le vôtre : pause, détour, reprise"),
                       ("L'accès", "Un paiement, un an")],
        "prod_h2": "Le Reykjavík City Walking Tour",
        "prod_lead": "Écrit par des journalistes et des historiens, raconté par Y'Own — un pêcheur de Reykjavik qui a du temps devant lui avant de reprendre la mer.",
        "prod_alt": "L'application TouringBee affichant le parcours de Reykjavik, tenue devant Hallgrímskirkja",
        "ticks": ["<strong>27 étapes audio</strong> — Hallgrímskirkja, le Sun Voyager, Harpa, le musée du punk, l'ICGV Óðinn, Þúfa et le reste",
                  "<strong>Carte GPS hors ligne</strong> : elle montre où vous êtes, mais c'est vous qui lancez chaque enregistrement une fois sur place",
                  "<strong>Illustrations</strong> pour savoir quel bâtiment vous avez sous les yeux",
                  "<strong>Livraison immédiate</strong> — l'e-mail d'activation arrive en quelques minutes",
                  "<strong>Ni groupe ni horaire</strong> — vous partez le jour et à l'heure qui vous arrangent"],
        "why_h2": "Pourquoi Reykjavik mérite mieux qu'une escale",
        "why_p1": "Il y a mille ans, un Norvégien nommé Ingólfur Arnarson a jeté par-dessus bord les montants sculptés de son siège d'honneur : aux dieux de choisir où il vivrait. Ses esclaves ont mis trois ans à les retrouver, échoués dans une baie pleine de vapeur. Il l'a appelée <em>Reykjavík</em>, la baie fumante. Cette vapeur explique encore pourquoi l'eau de votre douche sent le soufre.",
        "why_p2": "Les mille ans suivants, d'autres ont gouverné à sa place. La Norvège, puis le Danemark, puis un monopole commercial piloté depuis Copenhague, qui a étranglé l'économie deux siècles durant. L'indépendance est venue par étapes et ne s'est achevée qu'en 1944. C'est hier, à l'échelle d'une vie — et ça se sent : ce pays s'étonne encore un peu de se gouverner lui-même.",
        "why_img1_alt": "La maison du gouvernement à Reykjavik, avec une statue devant",
        "why_img2_alt": "Une visiteuse passe devant le Sun Voyager, sur le front de mer de Sæbraut, en hiver",
        "light_h3": "Ici, tout dépend de la lumière",
        "light_p1": "C'est le ciel qui commande, pas votre planning. De mai à juillet, le soleil ne se couche presque pas et la ville veille avec lui. En novembre et décembre, il vous reste quatre ou cinq heures de vraie lumière — et tout votre programme doit y tenir.",
        "light_p2": "En échange : les aurores. De septembre à avril environ, par nuit noire et ciel dégagé, on les voit depuis la ville. On se poste au phare de Grótta ou sur le front de mer de Sæbraut. Ni la saison ni une excursion ne garantissent quoi que ce soit. Un ciel clair, si.",
        "light_link": ("quand-partir-reykjavik", "Quand venir"),
        "free_h3": "Presque tout est gratuit",
        "free_p": "La balade ne coûte rien. Le centre de Reykjavik est un musée à ciel ouvert : les fresques, le port, l'étang, le parlement, la rue arc-en-ciel. Les sites payants se comptent sur les doigts d'une main : l'ascenseur de la tour de Hallgrímskirkja, Perlan, les musées et les bassins géothermaux — quelques centaines de couronnes, largement rentabilisées. Gardez votre budget pour les excursions. C'est là que l'Islande devient chère.",
        "free_link": ("budget-reykjavik", "Ce que coûte vraiment Reykjavik"),
        "weird_h3": "Une ville qui assume ses bizarreries",
        "weird_p1": "Reykjavik a un musée du phallus, un musée du punk installé dans d'anciennes toilettes publiques, une fresque de vampire et une locomotive à vapeur qui n'a jamais eu de voie ferrée. Pendant dix-sept ans, la télévision s'arrêtait en juillet pour que les gens sortent. Une fois, la ville a fait tomber un gouvernement à coups de casseroles.",
        "weird_p2": "Rien de tout cela sur les cartes postales. Tout, en revanche, sur le parcours.",
        "weird_img_alt": "La locomotive à vapeur conservée près du vieux port de Reykjavik",
        "oneday_link": ("un-jour-a-reykjavik", "Voir le plan d'une journée"),
        "tiles_h2": "Ce que vous verrez en chemin",
        "tiles_lead": "Six étapes sur vingt-sept. Les autres, vous les rencontrerez en marchant.",
        "tiles": [
            {"href": "hallgrimskirkja", "img": "tile-hallgrimskirkja", "h": "Hallgrímskirkja",
             "alt": "L'église Hallgrímskirkja vue d'en bas, drapeau islandais au vent",
             "p": "L'église en colonnes de basalte, et la meilleure vue de la ville depuis sa tour"},
            {"href": "rue-arc-en-ciel-laugavegur", "img": "tile-rainbow-street", "h": "La rue arc-en-ciel",
             "alt": "Skólavörðustígur, la rue peinte en arc-en-ciel qui monte vers Hallgrímskirkja",
             "p": "Skólavörðustígur, peinte pour la Pride et jamais effacée"},
            {"href": "harpa", "img": "tile-harpa", "h": "Harpa",
             "alt": "La façade en nid d'abeille de verre de la salle Harpa au crépuscule",
             "p": "Une ruche de verre bâtie pendant un krach qui a failli l'emporter"},
            {"href": "vieux-port-reykjavik", "img": "tile-old-harbour", "h": "Le vieux port",
             "alt": "Bateaux de pêche amarrés au vieux port de Reykjavik",
             "p": "D'où partent les bateaux à baleines — et où les guerres de la morue se sont gagnées"},
            {"href": "que-voir-a-reykjavik", "img": "tile-whales", "h": "Whales of Iceland",
             "alt": "Baleines grandeur nature éclairées en bleu dans l'exposition Whales of Iceland",
             "p": "Vingt-trois baleines grandeur nature dans un hangar sombre, au bord de l'eau"},
            {"href": "que-voir-a-reykjavik", "img": "tile-thufa", "h": "Þúfa",
             "alt": "Þúfa, la butte en spirale couverte d'herbe avec sa cabane à sécher le poisson",
             "p": "La fin du parcours : une colline en spirale coiffée d'un séchoir à poisson"}],
        "how_h2": "Comment fonctionne l'audioguide",
        "steps": [{"h": "Achetez", "p": "Un paiement sur cette page. L'e-mail d'activation arrive en quelques minutes."},
                  {"h": "Téléchargez", "p": "Installez l'application TouringBee, activez votre achat et téléchargez la visite en Wi-Fi à l'hôtel."},
                  {"h": "Marchez", "p": "La carte hors ligne montre où vous êtes. Arrivé à une étape, vous lancez la lecture — l'application ne vous coupe jamais la parole."},
                  {"h": "Gardez-la", "p": "Un an d'accès. Revenez en hiver et refaites le même parcours dans le noir."}],
        "how_note": "Prenez des écouteurs. Le vent islandais couvre le haut-parleur de votre téléphone.",
        "basics_h2": "Reykjavik en pratique",
        "facts": [("Arriver", "Keflavík (KEF), ~45 min en Flybus ou en voiture"),
                  ("Monnaie", "Couronne islandaise (ISK) — carte partout, espèces quasi jamais"),
                  ("Se déplacer", "À pied au centre, bus Strætó, voiture pour les excursions"),
                  ("Langue", "Islandais ; l'anglais se parle absolument partout"),
                  ("Saison des aurores", "~septembre à avril, nuits noires et dégagées seulement"),
                  ("Soleil de minuit", "~mai à juillet, quasiment aucune vraie nuit"),
                  ("Météo", "Change d'heure en heure. Des couches imperméables, pas un parapluie"),
                  ("Eau du robinet", "Excellente et gratuite. N'achetez jamais de bouteille ici")],
        "book_h3": "Réservez les payants avant de partir",
        "book_p": "Reykjavik affiche rarement complet. Ce pour quoi les gens prennent l'avion, en revanche, oui : Blue Lagoon, Sky Lagoon, sorties aurores en bateau et Cercle d'Or en été. Réserver à l'avance évite aussi de réorganiser la balade autour d'une file d'attente.",
        "book_cta": "Billets Reykjavik sur Tiqets",
        "partners_h2": "Excursions et billets",
        "partners_lead": "La balade couvre la ville. Tout ce qui suit se passe en dehors — et ce sont les réservations à boucler avant d'atterrir.",
        "p_golden_h": "Le Cercle d'Or",
        "p_golden_p": "Trois sites, une longue journée : la boucle islandaise classique, et la plus fréquentée.",
        "p_blue_p": "Près de l'aéroport : parfait en première ou dernière étape. Les créneaux partent vite.",
        "p_blue_alt": "Le spa géothermal Blue Lagoon, vapeur au-dessus d'une eau bleu laiteux",
        "p_aurora_h": "Aurores boréales",
        "p_aurora_p": "Bateaux et minibus qui courent après le ciel dégagé. La plupart vous replacent gratuitement si ça se couvre.",
        "p_aurora_alt": "Aurores boréales vertes au-dessus d'une route près de Reykjavik",
        "p_sky_p": "L'alternative urbaine au Blue Lagoon : plus proche, moins chère d'accès, même vapeur.",
        "p_sky_alt": "Un bassin géothermal éclairé en bleu le soir, près de Reykjavik",
        "car_h3": "Vous conduisez ? Réservez tôt",
        "car_p": "Le Cercle d'Or et la côte sud sont bien meilleurs au volant : vous vous arrêtez où vous voulez et vous échappez à l'horaire du car. Le parc de location islandais est petit, et en été tout part des semaines à l'avance. C'est l'une des rares réservations à boucler avant de décoller.",
        "car_cta": "Comparer les locations",
        "car_link": ("cercle-dor-voiture-ou-excursion", "Voiture ou excursion ?"),
        "cross_h2": "Les autres balades audio TouringBee",
        "cross_lead": "L'Islande a commercé avec Copenhague deux siècles durant — sous contrainte. La visite raconte cette histoire ; autant entendre l'autre version.",
        "cross": [{"h": "Copenhague", "path": "product/copenhagen-city-tour",
                   "p": "La ville qui a tenu l'économie islandaise deux cents ans, parcourue en trois heures environ.",
                   "cta": "Copenhagen Walking Tour"},
                  {"h": "Oslo", "path": "product/oslo-city-tour",
                   "p": "Le point de départ, à peu près, d'Ingólfur Arnarson — et le début des sagas.",
                   "cta": "Oslo City Walking Tour"},
                  {"h": "Tout le catalogue", "path": "shop-tbee",
                   "p": "Une centaine de balades audio en autonomie, en Europe et ailleurs.",
                   "cta": "Voir la boutique"}],
        "plan_h2": "Préparer votre visite",
        "plan": [{"h": "Y aller", "links": [("aeroport-keflavik-reykjavik", "Aéroport de Keflavík"), ("se-deplacer-a-reykjavik", "Se déplacer")]},
                 {"h": "Excursions", "links": [("cercle-dor", "Cercle d'Or"), ("cote-sud-islande", "Côte sud"), ("excursions-depuis-reykjavik", "Toutes les excursions")]},
                 {"h": "Le timing", "links": [("quand-partir-reykjavik", "Quand partir"), ("quoi-emporter-islande", "Quoi emporter"), ("aurores-boreales-reykjavik", "Aurores boréales")]},
                 {"h": "En ville", "links": [("hallgrimskirkja", "Hallgrímskirkja"), ("perlan", "Perlan"), ("street-art-reykjavik", "Street art")]},
                 {"h": "L'eau", "links": [("blue-lagoon", "Blue Lagoon"), ("sky-lagoon", "Sky Lagoon"), ("piscines-geothermales-reykjavik", "Bassins de la ville")]},
                 {"h": "Pratique", "links": [("budget-reykjavik", "Le budget"), ("ou-loger-a-reykjavik", "Où loger"), ("cuisine-islandaise", "Quoi manger")]}],
        "faq_h2": "Questions fréquentes",
        "faq": [
            ("Combien de jours faut-il à Reykjavik ?", "Deux journées pleines suffisent pour la ville : une pour la balade et les musées, une pour un bassin géothermal ou le port. Ajoutez un jour par grande excursion — un pour le Cercle d'Or, un pour la côte sud. On sous-estime presque toujours le temps passé en véhicule pendant un séjour en Islande."),
            ("Le centre se fait-il à pied ?", "Entièrement. Les 27 étapes représentent environ 5 km, quasiment sans dénivelé, sauf la montée de Skólavörðustígur vers l'église. La contrainte, c'est la météo, pas la distance."),
            ("L'audioguide se déclenche-t-il tout seul en marchant ?", "Non, et c'est voulu. La carte hors ligne montre où vous êtes, mais c'est vous qui lancez la lecture en arrivant. La précision du GPS d'un téléphone varie trop pour que le déclenchement automatique soit fiable. En manuel, vous ne ratez jamais une histoire parce que votre téléphone vous croyait dans la rue d'à côté."),
            ("Faut-il de la data pendant la balade ?", "Non. Téléchargez la visite une fois en Wi-Fi : tout fonctionne hors ligne, carte comprise."),
            ("Peut-on voir les aurores depuis Reykjavik même ?", "Oui, par nuit noire et ciel dégagé, de septembre à avril environ. Le phare de Grótta, sur Seltjarnarnes, et la portion sombre du front de mer de Sæbraut sont les spots habituels. La pollution lumineuse du centre joue contre vous, et les nuages l'emportent sur tout : aucune saison ni aucune excursion ne peut promettre une aurore."),
            ("Reykjavik est-elle chère ?", "Les restaurants et l'alcool, oui, franchement. La ville, non : la balade, le port, les fresques et les parcs sont gratuits, l'eau du robinet est excellente, et les bassins géothermaux coûtent une fraction du Blue Lagoon. Le budget part dans les excursions et les dîners."),
            ("Comment s'habiller ?", "Veste imperméable, couche chaude, chaussures antidérapantes et bonnet, quel que soit le mois. Le parapluie ne sert à rien : le vent de Reykjavik le détruira, et les habitants le remarqueront."),
            ("L'audioguide existe-t-il en français ?", "Le Reykjavík City Walking Tour est pour l'instant raconté en anglais. D'autres visites TouringBee existent en huit langues."),
        ],
        "final_h2": "Marchez, et écoutez pourquoi",
        "final_p": "Vingt-sept étapes, deux heures et demie, et un pêcheur nommé Y'Own qui vous explique pourquoi rien de tout cela n'est ce que vous croyez voir.",
        "final_cta2": "Voir les excursions",
    },

    "legal": {
        "privacy": '''<h2>Qui édite ce site</h2>
<p>reykjavikwalk.com est publié par Touringbee Limited, société immatriculée en République d'Irlande sous le numéro 660321. Écrivez-nous à <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>
<h2>Ce que nous collectons</h2>
<p>Aucun compte à créer, aucun nom, aucune adresse, aucune donnée bancaire collectée sur ce site. Si vous achetez l'audioguide, le paiement passe par Bókun et Stripe : vos coordonnées bancaires sont traitées par eux, jamais par nous.</p>
<p>Comme presque tous les sites, notre hébergeur enregistre des journaux serveur standard : adresse IP, type de navigateur, page demandée et horodatage. Ils servent au bon fonctionnement et à la sécurité du site.</p>
<h2>Mesure d'audience et cookies</h2>
<p>Nous utilisons une mesure d'audience respectueuse de la vie privée pour compter les pages vues et savoir quels guides servent. Nous ne vendons aucune donnée et n'affichons aucune régie publicitaire.</p>
<p>Quand vous suivez un lien affilié vers un partenaire (GetYourGuide, Tiqets, Booking.com), ce partenaire peut déposer un cookie pour nous attribuer la réservation. Sa politique s'applique dès que vous êtes sur son site.</p>
<h2>L'audioguide</h2>
<p>Les achats du Reykjavík City Walking Tour sont gérés par Bókun (paiement) et TouringBee (envoi du lien d'activation). Leurs conditions : <a href="https://touringbee.com/terms-and-conditions-of-use/" target="_blank" rel="noopener">touringbee.com/terms-and-conditions-of-use</a>.</p>
<h2>Vos droits</h2>
<p>Dans l'UE et au Royaume-Uni, vous pouvez demander quelles données personnelles nous détenons, les faire corriger ou supprimer. Écrivez à <a href="mailto:info@touringbee.com">info@touringbee.com</a> : nous répondons sous 30 jours.</p>''',
        "affiliate": '''<p>Certains liens de reykjavikwalk.com sont des liens affiliés. Si vous réservez ou achetez via l'un d'eux, nous touchons une commission. Cela ne vous coûte rien de plus : le prix est le même qu'en direct.</p>
<h2>Avec qui nous travaillons</h2>
<ul class="ticks">
<li><strong>GetYourGuide</strong> — excursions, aurores boréales, observation des baleines, transferts</li>
<li><strong>Tiqets</strong> — billets de sites et de bains géothermaux</li>
<li><strong>Booking.com</strong> — hôtels et location de voiture</li>
</ul>
<h2>Notre propre produit</h2>
<p>L'audioguide Reykjavík City Walking Tour est fabriqué par TouringBee, qui édite ce site. Nous ne sommes pas neutres : nous pensons que c'est la meilleure façon de parcourir Reykjavik, et nous le disons. Vous pouvez l'acheter ici ou directement chez TouringBee, au même prix.</p>
<h2>Ce que ça change à nos recommandations</h2>
<p>La commission ne décide jamais du contenu d'un guide. Nous recommandons plusieurs fois les bassins géothermaux plutôt que le Blue Lagoon, alors que le Blue Lagoon paie mieux, et nous disons quelles attractions ne valent pas leur prix. Une recommandation qui n'existe que parce qu'elle rapporte n'est pas une recommandation.</p>
<p>Prix, horaires et disponibilités changent. Vérifiez toujours sur le site de l'opérateur avant de partir.</p>
<p>Questions : <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>''',
    },
}
