# -*- coding: utf-8 -*-
"""Polski — bezpośrednio, bez sztywnego Pan/Pani. Bez „perełka”, „zapierający dech”, „must-see”."""

G = [
    ("P0", "zloty-krag", "Złoty Krąg z Reykjaviku", "Þingvellir, Geysir i Gullfoss w jeden dzień — autem albo z wycieczką."),
    ("P0", "blue-lagoon", "Blue Lagoon: bilety i dojazd", "Jak wcisnąć ją między loty i czy cena się broni."),
    ("P0", "zorza-polarna-reykjavik", "Zorza polarna w Reykjaviku", "Sezon, prognoza, miejsca w mieście i kiedy wycieczka faktycznie pomaga."),
    ("P0", "hallgrimskirkja", "Hallgrímskirkja i wieża", "Kościół, winda, kolejka i najlepsza pora, żeby wjechać."),
    ("P0", "lotnisko-keflavik-reykjavik", "Z lotniska Keflavík do centrum", "Flybus, transfer prywatny, auto z wypożyczalni — koszt i czas."),
    ("P0", "sky-lagoon", "Sky Lagoon", "Geotermalne spa u bram miasta i jego siedmioetapowy rytuał."),
    ("P0", "wieloryby-reykjavik", "Wieloryby i maskonury", "Łodzie ze starego portu, sezony i choroba morska."),
    ("P0", "kiedy-jechac-do-reykjaviku", "Kiedy jechać do Reykjaviku", "Światło, zorze, pogoda i ceny, miesiąc po miesiącu."),
    ("P0", "jeden-dzien-w-reykjaviku", "Jeden dzień w Reykjaviku", "Trasa pieszo, w którą wchodzi to, co najważniejsze."),
    ("P0", "co-zobaczyc-w-reykjaviku", "Co zobaczyć w Reykjaviku", "Pełna lista, ułożona według tego, co warte twoich godzin światła."),
    ("P1", "zloty-krag-auto-czy-wycieczka", "Złoty Krąg: auto czy wycieczka?", "Uczciwe porównanie kosztów i czasu."),
    ("P1", "wycieczki-z-reykjaviku", "Wycieczki z Reykjaviku", "Wszystkie, które są tego warte, z czasami przejazdu."),
    ("P1", "poludniowe-wybrzeze-islandii", "Południowe wybrzeże w jeden dzień", "Seljalandsfoss, Skógafoss i czarna plaża Reynisfjara."),
    ("P1", "sun-voyager", "Sun Voyager i nadbrzeże", "Rzeźba, którą fotografują wszyscy — i co naprawdę przedstawia."),
    ("P1", "harpa", "Harpa, sala koncertowa", "Szklany plaster miodu i to, jak przetrwał krach."),
    ("P1", "stary-port-reykjavik", "Stary port", "Łodzie, jedzenie, okręt straży przybrzeżnej i wojny dorszowe."),
    ("P1", "tecza-laugavegur", "Tęczowa ulica i Laugavegur", "Malowana uliczka i główny deptak handlowy."),
    ("P1", "perlan", "Perlan", "Kopuła, jaskinia lodowa i taras widokowy."),
    ("P1", "dwa-dni-w-reykjaviku", "Dwa dni w Reykjaviku", "Wolniejszy plan, z miejscem na laguny."),
    ("P1", "co-zabrac-na-islandie", "Co zabrać i jak się ubrać", "Warstwy, które wytrzymują pogodę zmieniającą się co godzinę."),
    ("P1", "komunikacja-w-reykjaviku", "Jak się poruszać po Reykjaviku", "Pieszo, autobusami Strætó i kiedy naprawdę potrzebne jest auto."),
    ("P1", "ceny-w-reykjaviku", "Czy Reykjavik jest drogi?", "Ile naprawdę kosztują rzeczy i gdzie da się zaoszczędzić."),
    ("P1", "gdzie-spac-w-reykjaviku", "Gdzie spać w Reykjaviku", "Dzielnice po kolei i to, za co się w nich płaci."),
    ("P2", "street-art-reykjavik", "Street art w Reykjaviku", "Murale, łącznie z wampirem, którego nikt nie tłumaczy."),
    ("P2", "latarnia-grotta", "Grótta i najlepsze miejsca na zorzę", "Gdzie stanąć, kiedy niebo robi się zielone."),
    ("P2", "tjornin-austurvollur-parlament", "Tjörnin, Austurvöllur i Alþingi", "Staw, plac i najstarszy parlament świata."),
    ("P2", "kuchnia-islandzka", "Kuchnia islandzka", "Pylsa, skyr, zupa jagnięca, hákarl — co spróbować, a co odpuścić."),
    ("P2", "baseny-geotermalne-reykjavik", "Baseny geotermalne i zasady", "Zasady prysznica, o których nikt turystów nie uprzedza."),
    ("P2", "reykjavik-za-darmo", "Reykjavik za darmo", "Cały dzień, który nic nie kosztuje."),
    ("P2", "muzea-reykjavik", "Muzea Reykjaviku", "Muzeum Narodowe, wystawa 871±2 i te dziwniejsze."),
]

CONTENT = {
    "slugs": {"guides": "przewodniki", "privacy": "polityka-prywatnosci",
              "affiliate": "informacja-o-afiliacji"},
    "guides": [{"wave": w, "slug": s, "title": t, "desc": d} for w, s, t, d in G],

    "ui": {
        "menu": "Przewodniki", "menu_all": "Wszystkie przewodniki",
        "buy": "Kup audioprzewodnik — 9,99 €",
        "see_tours": "Zobacz wycieczki", "check_tickets": "Zobacz bilety",
        "sticky_title": "Reykjavík City Walking Tour — 9,99 €",
        "sticky_sub": "4,7 ★ · 27 przystanków · offline · po angielsku",
        "sticky_btn": "Kup teraz",
        "rating_aria": "Ocena 4,7 na 5",
        "rating_label": "średnia ocena podróżnych",
        "price_display": "9,99 €",
        "price_sub": "Jedna płatność · bez abonamentu · dostęp na rok",
        "checkout_note": "Bezpieczna płatność na tej stronie. Wolisz sklep?",
        "open_shop": "Otwórz w TouringBee",
        "audio_fallback": "Twoja przeglądarka nie odtwarza dźwięku.",
        "product_name": "Reykjavík City Walking Tour",
        "product_name_full": "Reykjavík City Walking Tour — audioprzewodnik na własną rękę",
        "product_desc": "Spacer po Reykjaviku na własną rękę: 27 przystanków, audio i mapa GPS offline, od pomnika Ingólfura Arnarsona do Þúfy. Około 2–2,5 godziny.",
        "product_category": "Audioprzewodnik na własną rękę",
        "author_h": "O autorze",
        "author_alt": "Eugene, autor audioprzewodników TouringBee",
        "author_bio": "Eugene od szesnastu lat mieszka we Francji, pracował jako przewodnik i założył sieć treści podróżniczych paris10.travel. Odwiedził ponad 300 francuskich miast i wsi, a dziś pisze audioprzewodniki TouringBee. Te przewodniki układa tak, jakby instruował znajomego przed wyjazdem: co naprawdę warte czasu, co zarezerwować, a co spokojnie odpuścić.",
        "author_bio_plain": "Były przewodnik, założyciel paris10.travel, autor audioprzewodników TouringBee.",
        "f_explore": "Odkryj", "f_product": "Audioprzewodnik", "f_legal": "Informacje prawne",
        "f_langs": "Języki", "f_alltours": "Wszystkie trasy TouringBee",
        "f_terms": "Regulamin",
        "langnames": {"en": "English", "fr": "Français", "de": "Deutsch", "es": "Español",
                      "it": "Italiano", "pt": "Português", "pl": "Polski", "ru": "Русский"},
        "disclaimer": "reykjavikwalk.com wydaje Touringbee Limited (Irlandia, spółka nr 660321). Część linków na tej stronie to linki afiliacyjne: jeśli przez nie zarezerwujesz, dostajemy prowizję — bez dodatkowego kosztu dla ciebie. Ceny i godziny się zmieniają; przed wyjazdem zawsze sprawdź na stronie oficjalnej.",
        "guides_h1": "Wszystkie przewodniki po Reykjaviku",
        "guides_title": "Wszystkie przewodniki po Reykjaviku | TouringBee",
        "guides_meta": "Wszystkie przewodniki na reykjavikwalk.com: Złoty Krąg, Blue Lagoon, zorza polarna, Hallgrímskirkja, dojazd z lotniska, plany dnia i więcej.",
        "guides_lead": 'Trzydzieści przewodników po Reykjaviku i wypadach, które się z niego robi — publikowane falami. Zacznij od <a href="/pl/">pełnego przewodnika po Reykjaviku</a>; wszystko poniżej wchodzi głębiej w jeden wątek.',
        "in_production": "W przygotowaniu",
        "waves": {"P0": "Pierwsza fala — właśnie powstaje",
                  "P1": "Druga fala", "P2": "Trzecia fala"},
        "updated": "Ostatnia aktualizacja: 6 sierpnia 2026",
        "privacy_title": "Polityka prywatności",
        "privacy_meta": "Jak reykjavikwalk.com obchodzi się z danymi, plikami cookie i śledzeniem afiliacyjnym.",
        "affiliate_title": "Informacja o afiliacji",
        "affiliate_meta": "Które linki na reykjavikwalk.com są afiliacyjne, z kim współpracujemy i co to zmienia w naszych rekomendacjach.",
        "nf_h1": "Tej strony tu nie ma",
        "nf_p": "Albo jeszcze jej nie opublikowaliśmy, albo link jest zły. Jedno i drugie da się naprawić.",
        "nf_cta1": "Pełny przewodnik po Reykjaviku",
    },

    "home": {
        "city": "Reykjavik",
        "city_desc": "Stolica Islandii i najdalej na północ wysunięta stolica świata.",
        "title": "Co zobaczyć w Reykjaviku: spacer i wycieczki | TouringBee",
        "meta": "Przygotuj Reykjavik porządnie: spacer na własną rękę z 27 przystankami i audio offline, do tego Złoty Krąg, Blue Lagoon, zorza polarna i wszystko, w czym najdalej wysunięta na północ stolica świata jest najlepsza.",
        "hero_alt": "Rzeźba Sun Voyager na nadbrzeżu Reykjaviku pod szerokim islandzkim niebem",
        "chip": "27 przystanków · 2–2,5 godziny · działa offline",
        "h1": "Reykjavik pieszo, we własnym tempie",
        "sub": "Najdalej na północ wysuniętą stolicę świata da się obejść w jedno popołudnie — jeśli wiesz, na co patrzysz. To pełny przewodnik: sama trasa, wycieczki warte rezerwacji i pory roku, które zmieniają wszystko.",
        "cta_inside": "Zobacz, co w środku", "cta_preview": "Posłuchaj fragmentu",
        "cta_daytrips": "Wycieczki",
        "intro1": "Reykjavik jest mały. Około 140 tysięcy mieszkańców, stare centrum przechodzi się w dwadzieścia minut, a prawie wszystko, po co tu przyjeżdżasz, leży przy tej jednej trasie. Reszta to dwadzieścia minut autobusem.",
        "intro2": "I to jest pułapka. Miasto wygląda na takie, które da się „zaliczyć” w jeden poranek. Więc robi się zdjęcie kościołowi, zdjęcie Sun Voyagerowi i wyjeżdża. Nie usłyszawszy, jak naród rybaków pokonał Royal Navy. Ani dlaczego w 2013 roku przesunięto gotowy już projekt drogi: mieszkańcy ujęli się za elfami.",
        "intro3": 'Chodzi o historie. Dlatego powstał <a href="#audio">Reykjavík City Walking Tour</a>: 27 przystanków, od pomnika założyciela miasta do porośniętego trawą kopca przy porcie, z suszarnią ryb na szczycie. Włączasz nagranie, idziesz, zatrzymujesz się, gdzie chcesz. Dwie i pół godziny. Albo całe popołudnie, jeśli będziesz przystawać na kawę. A będziesz.',
        "preview_h": "Posłuchaj początku",
        "preview_p": "30 sekund ze wstępu, po angielsku",
        "highlights": [("Trasa", "Od Arnarhóll do Þúfy, 27 numerowanych przystanków"),
                       ("Działa na", "iPhonie i Androidzie, w pełni offline"),
                       ("Tempo", "Twoje — pauza, objazd, dalej"),
                       ("Dostęp", "Jedna płatność, jeden rok")],
        "prod_h2": "Reykjavík City Walking Tour",
        "prod_lead": "Napisany przez dziennikarzy i historyków, opowiedziany głosem Y'Owna — rybaka z Reykjaviku, który ma trochę czasu przed kolejnym wyjściem w morze.",
        "prod_alt": "Aplikacja TouringBee z trasą po Reykjaviku, trzymana przed Hallgrímskirkją",
        "ticks": ["<strong>27 przystanków audio</strong>: Hallgrímskirkja, Sun Voyager, Harpa, muzeum punka, ICGV Óðinn, Þúfa i więcej",
                  "<strong>Mapa GPS offline</strong> pokazuje, gdzie jesteś — nagranie włączasz sam, kiedy dojdziesz na miejsce",
                  "<strong>Ilustracje</strong>, żebyś wiedział, na który budynek patrzysz",
                  "<strong>Dostawa od razu</strong> — mail aktywacyjny przychodzi w kilka minut",
                  "<strong>Bez grupy i bez godzin</strong> — ruszasz w dowolny dzień i o dowolnej porze"],
        "why_h2": "Dlaczego Reykjavik zasługuje na więcej niż przesiadkę",
        "why_p1": "Tysiąc lat temu Norweg Ingólfur Arnarson wyrzucił za burtę rzeźbione słupy swojego honorowego siedziska i pozwolił bogom wybrać, gdzie zamieszka. Jego niewolnicy szukali ich trzy lata; znaleźli w zatoce pełnej pary. Nazwał ją <em>Reykjavík</em> — dymiąca zatoka. Ta sama para do dziś odpowiada za to, że woda pod prysznicem pachnie tu siarką.",
        "why_p2": "Kolejny tysiąc lat Islandia spędziła pod cudzą władzą. Norwegia, potem Dania, potem monopol handlowy sterowany z Kopenhagi, który przez dwa stulecia dusił gospodarkę. Niepodległość przychodziła etapami i domknęła się dopiero w 1944 roku. To pamięć jednego pokolenia — i to czuć: ten kraj wciąż trochę się dziwi, że rządzi sam sobą.",
        "why_img1_alt": "Siedziba rządu w Reykjaviku z pomnikiem przed wejściem",
        "why_img2_alt": "Zimą turystka mija rzeźbę Sun Voyager na nadbrzeżu Sæbraut",
        "light_h3": "Tu wszystko zależy od światła",
        "light_p1": "Nic nie kształtuje pobytu w Reykjaviku tak jak niebo. Od maja do lipca słońce prawie nie zachodzi, a miasto nie kładzie się razem z nim. W listopadzie i grudniu masz cztery, może pięć godzin użytecznego światła — i wszystko, co zaplanujesz, musi się w nich zmieścić.",
        "light_p2": "W zamian dostajesz zorzę. Mniej więcej od września do kwietnia, w ciemną i bezchmurną noc, widać ją nawet z miasta: latarnia Grótta i nadbrzeże Sæbraut to sprawdzone punkty. Ani sezon, ani wycieczka niczego nie gwarantują. Czyste niebo owszem.",
        "light_link": ("kiedy-jechac-do-reykjaviku", "Kiedy przyjechać"),
        "free_h3": "Prawie wszystko jest za darmo",
        "free_p": "Sam spacer nic nie kosztuje. Centrum Reykjaviku to muzeum pod gołym niebem: murale, port, staw, parlament, tęczowa ulica. Płatnych rzeczy jest niewiele: winda na wieżę Hallgrímskirkji, Perlan, muzea i baseny geotermalne — kilkaset koron, dobrze wydanych. Budżet zostaw na wycieczki. To tam Islandia robi się droga.",
        "free_link": ("ceny-w-reykjaviku", "Ile naprawdę kosztuje Reykjavik"),
        "weird_h3": "Miasto, które nie wstydzi się swoich dziwactw",
        "weird_p1": "Reykjavik ma muzeum fallusa, muzeum punka urządzone w dawnym szalecie miejskim, mural z wampirem i parowóz, który nigdy nie miał po czym jeździć. Przez siedemnaście lat telewizja robiła w lipcu przerwę, żeby ludzie wychodzili z domu. A raz miasto obaliło rząd, waląc w garnki.",
        "weird_p2": "Na pocztówki nic z tego nie trafia. Na trasie jest wszystko.",
        "weird_img_alt": "Zachowany parowóz przy starym porcie w Reykjaviku",
        "oneday_link": ("jeden-dzien-w-reykjaviku", "Zobacz plan na jeden dzień"),
        "tiles_h2": "Co zobaczysz po drodze",
        "tiles_lead": "Sześć z dwudziestu siedmiu przystanków. Resztę spotkasz po drodze.",
        "tiles": [
            {"href": "hallgrimskirkja", "img": "tile-hallgrimskirkja", "h": "Hallgrímskirkja",
             "alt": "Kościół Hallgrímskirkja od dołu, z powiewającą flagą Islandii",
             "p": "Kościół z bazaltowych kolumn, a z jego wieży najlepszy widok w mieście"},
            {"href": "tecza-laugavegur", "img": "tile-rainbow-street", "h": "Tęczowa ulica",
             "alt": "Skólavörðustígur, ulica pomalowana w tęczę, prowadząca pod Hallgrímskirkję",
             "p": "Skólavörðustígur — pomalowana na Paradę i nigdy nie zmyta"},
            {"href": "harpa", "img": "tile-harpa", "h": "Harpa",
             "alt": "Szklana fasada w kształcie plastra miodu sali Harpa o zmierzchu",
             "p": "Szklany plaster miodu budowany w środku krachu, który omal go nie pogrzebał"},
            {"href": "stary-port-reykjavik", "img": "tile-old-harbour", "h": "Stary port",
             "alt": "Kutry rybackie przy starym porcie w Reykjaviku",
             "p": "Stąd wypływają łodzie na wieloryby — i tu wygrano wojny dorszowe"},
            {"href": "co-zobaczyc-w-reykjaviku", "img": "tile-whales", "h": "Whales of Iceland",
             "alt": "Modele wielorybów naturalnej wielkości podświetlone na niebiesko na wystawie Whales of Iceland",
             "p": "Dwadzieścia trzy wieloryby naturalnej wielkości w ciemnej hali nad wodą"},
            {"href": "co-zobaczyc-w-reykjaviku", "img": "tile-thufa", "h": "Þúfa",
             "alt": "Þúfa, porośnięty trawą spiralny kopiec z suszarnią ryb na szczycie",
             "p": "Koniec trasy: spiralne wzgórze z suszarnią ryb na wierzchołku"}],
        "how_h2": "Jak działa audioprzewodnik",
        "steps": [{"h": "Kup", "p": "Jedna płatność na tej stronie. Mail aktywacyjny przychodzi w kilka minut."},
                  {"h": "Pobierz", "p": "Zainstaluj darmową aplikację TouringBee, aktywuj zakup i ściągnij trasę na hotelowym wi-fi."},
                  {"h": "Idź", "p": "Mapa offline pokazuje, gdzie jesteś. Na przystanku włączasz nagranie — aplikacja nigdy nie wchodzi ci w słowo sama."},
                  {"h": "Zachowaj", "p": "Rok dostępu. Wróć zimą i przejdź tę samą trasę po ciemku."}],
        "how_note": "Weź słuchawki. Islandzki wiatr jest głośniejszy niż głośnik w telefonie.",
        "basics_h2": "Reykjavik w praktyce",
        "facts": [("Dojazd", "Keflavík (KEF), ok. 45 min Flybusem albo autem"),
                  ("Waluta", "Korona islandzka (ISK) — karta wszędzie, gotówka prawie nigdy"),
                  ("Poruszanie się", "Centrum pieszo, autobusy Strætó, auto na wycieczki"),
                  ("Język", "Islandzki; angielskim mówią praktycznie wszyscy"),
                  ("Sezon na zorzę", "ok. wrzesień–kwiecień, tylko ciemne i bezchmurne noce"),
                  ("Noce polarne latem", "ok. maj–lipiec, prawie bez prawdziwej ciemności"),
                  ("Pogoda", "Zmienia się co godzinę. Warstwy wodoodporne biją parasol"),
                  ("Woda z kranu", "Świetna i darmowa. Nie kupuj tu butelkowanej")],
        "book_h3": "Płatne atrakcje rezerwuj przed wyjazdem",
        "book_p": "Sam Reykjavik rzadko się wyprzedaje, ale to, po co ludzie tu lecą, owszem: Blue Lagoon, Sky Lagoon, łodzie na zorzę i latem Złoty Krąg. Dzięki wcześniejszej rezerwacji nie musisz też przestawiać całego spaceru pod kolejkę.",
        "book_cta": "Bilety do Reykjaviku na Tiqets",
        "partners_h2": "Wycieczki i bilety",
        "partners_lead": "Spacer obejmuje miasto. Wszystko poniżej dzieje się poza nim — i to są rezerwacje, które warto domknąć przed wylądowaniem.",
        "p_golden_h": "Złoty Krąg",
        "p_golden_p": "Trzy miejsca, jeden długi dzień: klasyczna islandzka pętla i najbardziej zatłoczona.",
        "p_blue_p": "Blisko lotniska, więc pasuje jako pierwszy albo ostatni punkt. Terminy schodzą szybko.",
        "p_blue_alt": "Geotermalne spa Blue Lagoon, para nad mlecznobłękitną wodą",
        "p_aurora_h": "Zorza polarna",
        "p_aurora_p": "Łodzie i busy goniące za czystym niebem. Większość przepisuje bilet za darmo, jeśli się zachmurzy.",
        "p_aurora_alt": "Zielona zorza polarna nad drogą pod Reykjavikiem",
        "p_sky_p": "Miejska alternatywa dla Blue Lagoon: bliżej, taniej dojechać, ta sama para.",
        "p_sky_alt": "Laguna geotermalna podświetlona na niebiesko wieczorem pod Reykjavikiem",
        "car_h3": "Jedziesz sam? Rezerwuj auto wcześnie",
        "car_p": "Złoty Krąg i południowe wybrzeże lepiej wychodzą własnym autem: zatrzymujesz się, gdzie chcesz, i nie patrzysz na rozkład autokaru. Islandzka flota wynajmu jest mała, a latem rozchodzi się na tygodnie przed terminem. To jedna z niewielu rezerwacji, którą naprawdę warto zrobić przed wylotem.",
        "car_cta": "Porównaj auta",
        "car_link": ("zloty-krag-auto-czy-wycieczka", "Auto czy wycieczka?"),
        "cross_h2": "Inne spacery audio od TouringBee",
        "cross_lead": "Islandia handlowała z Kopenhagą przez dwa stulecia — nie z własnej woli. Trasa opowiada tę historię; warto usłyszeć też drugą stronę.",
        "cross": [{"h": "Kopenhaga", "path": "product/copenhagen-city-tour",
                   "p": "Miasto, które przez dwieście lat prowadziło islandzką gospodarkę — pieszo w jakieś trzy godziny.",
                   "cta": "Copenhagen Walking Tour"},
                  {"h": "Oslo", "path": "product/oslo-city-tour",
                   "p": "Stamtąd mniej więcej wypłynął Ingólfur Arnarson — i tam zaczynają się sagi.",
                   "cta": "Oslo City Walking Tour"},
                  {"h": "Cały katalog", "path": "shop-tbee",
                   "p": "Około stu spacerów audio na własną rękę, w Europie i poza nią.",
                   "cta": "Zobacz sklep"}],
        "plan_h2": "Zaplanuj wyjazd",
        "plan": [{"h": "Dojazd", "links": [("lotnisko-keflavik-reykjavik", "Lotnisko Keflavík"), ("komunikacja-w-reykjaviku", "Poruszanie się")]},
                 {"h": "Wycieczki", "links": [("zloty-krag", "Złoty Krąg"), ("poludniowe-wybrzeze-islandii", "Południowe wybrzeże"), ("wycieczki-z-reykjaviku", "Wszystkie wycieczki")]},
                 {"h": "Termin", "links": [("kiedy-jechac-do-reykjaviku", "Kiedy jechać"), ("co-zabrac-na-islandie", "Co zabrać"), ("zorza-polarna-reykjavik", "Zorza polarna")]},
                 {"h": "W mieście", "links": [("hallgrimskirkja", "Hallgrímskirkja"), ("perlan", "Perlan"), ("street-art-reykjavik", "Street art")]},
                 {"h": "Woda", "links": [("blue-lagoon", "Blue Lagoon"), ("sky-lagoon", "Sky Lagoon"), ("baseny-geotermalne-reykjavik", "Baseny miejskie")]},
                 {"h": "Praktyka", "links": [("ceny-w-reykjaviku", "Ile to kosztuje"), ("gdzie-spac-w-reykjaviku", "Gdzie spać"), ("kuchnia-islandzka", "Co jeść")]}],
        "faq_h2": "Częste pytania",
        "faq": [
            ("Ile dni potrzeba na Reykjavik?", "Dwa pełne dni spokojnie wystarczą na miasto: jeden na spacer i muzea, drugi na lagunę albo port. Do tego po dniu na każdy większy wypad — jeden na Złoty Krąg, jeden na południowe wybrzeże. Prawie każdy nie docenia, ile czasu na Islandii spędza się w aucie albo w busie."),
            ("Czy centrum da się obejść pieszo?", "W całości. 27 przystanków to około 5 km praktycznie bez przewyższeń, poza podejściem Skólavörðustígur pod kościół. Ogranicza cię pogoda, nie dystans."),
            ("Czy audioprzewodnik włącza się sam podczas marszu?", "Nie, i to celowo. Mapa offline pokazuje, gdzie jesteś, ale nagranie włączasz sam po dojściu na miejsce. Dokładność GPS w telefonie waha się za bardzo, żeby automat był pewny. Ręcznie nie przegapisz historii tylko dlatego, że telefonowi wydawało się, że jesteś ulicę dalej."),
            ("Czy potrzebuję internetu w czasie spaceru?", "Nie. Pobierasz trasę raz na wi-fi i wszystko działa offline, razem z mapą."),
            ("Czy zorzę widać z samego Reykjaviku?", "Tak, w ciemną i bezchmurną noc mniej więcej od września do kwietnia. Standardowe miejsca to latarnia Grótta na Seltjarnarnesie i ciemniejszy odcinek nadbrzeża Sæbraut. Światła centrum działają przeciw tobie, a chmury biją wszystko: żaden sezon ani żadna wycieczka nie obiecają ci zorzy."),
            ("Czy Reykjavik jest drogi?", "Jedzenie na mieście i alkohol — tak, wyraźnie. Samo miasto nie: spacer, port, murale i parki są darmowe, woda z kranu jest świetna, a baseny geotermalne kosztują ułamek tego, co Blue Lagoon. Budżet schodzi na wycieczki i kolacje."),
            ("Jak się ubrać?", "Kurtka przeciwdeszczowa, ciepła warstwa środkowa, buty, które nie ślizgają się, i czapka — w każdym miesiącu. Parasol nie ma sensu: reykjavicki wiatr go zniszczy, a miejscowi to zauważą."),
            ("Czy audioprzewodnik jest po polsku?", "Reykjavík City Walking Tour jest na razie nagrany po angielsku. Inne trasy TouringBee są dostępne w ośmiu językach."),
        ],
        "final_h2": "Przejdź trasę i posłuchaj dlaczego",
        "final_p": "Dwadzieścia siedem przystanków, dwie i pół godziny i rybak o imieniu Y'Own tłumaczący, dlaczego nic z tego nie jest tym, na co wygląda.",
        "final_cta2": "Zobacz wycieczki",
    },

    "legal": {
        "privacy": '''<h2>Kto prowadzi tę stronę</h2>
<p>reykjavikwalk.com wydaje Touringbee Limited, spółka zarejestrowana w Republice Irlandii pod numerem 660321. Kontakt: <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>
<h2>Co zbieramy</h2>
<p>Nie musisz zakładać konta, a my nie zbieramy na tej stronie imion, adresów ani danych płatniczych. Przy zakupie audioprzewodnika kasę obsługuje Bókun, a płatność Stripe — dane karty trafiają do nich, nigdy do nas.</p>
<p>Jak prawie każda strona, nasz hosting zapisuje standardowe logi serwera: adres IP, typ przeglądarki, żądaną stronę i czas. Służą do utrzymania strony i bezpieczeństwa.</p>
<h2>Analityka i pliki cookie</h2>
<p>Korzystamy z analityki przyjaznej prywatności, żeby liczyć odsłony i wiedzieć, które przewodniki są przydatne. Nie sprzedajemy danych i nie prowadzimy tu sieci reklamowych.</p>
<p>Gdy klikniesz link afiliacyjny do partnera takiego jak GetYourGuide, Tiqets czy Booking.com, ten partner może zapisać cookie, żeby przypisać nam rezerwację. Od tego momentu obowiązuje jego polityka.</p>
<h2>Audioprzewodnik</h2>
<p>Zakupy Reykjavík City Walking Tour obsługują Bókun (płatność) i TouringBee (wysyłka linku aktywacyjnego). Ich regulamin: <a href="https://touringbee.com/terms-and-conditions-of-use/" target="_blank" rel="noopener">touringbee.com/terms-and-conditions-of-use</a>.</p>
<h2>Twoje prawa</h2>
<p>W UE i Wielkiej Brytanii możesz zapytać, jakie dane osobowe przechowujemy, zażądać ich poprawienia lub usunięcia. Napisz na <a href="mailto:info@touringbee.com">info@touringbee.com</a> — odpowiadamy w ciągu 30 dni.</p>''',
        "affiliate": '''<p>Część linków na reykjavikwalk.com to linki afiliacyjne. Jeśli przez nie zarezerwujesz lub kupisz, dostajemy prowizję. Ciebie to nic nie kosztuje więcej — cena jest taka sama jak bezpośrednio.</p>
<h2>Z kim współpracujemy</h2>
<ul class="ticks">
<li><strong>GetYourGuide</strong> — wycieczki, wyprawy na zorzę, wieloryby, transfery</li>
<li><strong>Tiqets</strong> — bilety do atrakcji i lagun</li>
<li><strong>Booking.com</strong> — hotele i wynajem aut</li>
</ul>
<h2>Nasz własny produkt</h2>
<p>Audioprzewodnik Reykjavík City Walking Tour robi TouringBee, wydawca tej strony. Nie jesteśmy tu bezstronni: uważamy, że to najlepszy sposób na przejście Reykjaviku, i mówimy to wprost. Możesz go kupić tutaj albo bezpośrednio w TouringBee, w tej samej cenie.</p>
<h2>Co to zmienia w tym, co piszemy</h2>
<p>Prowizja nigdy nie decyduje o treści przewodnika. W kilku miejscach polecamy miejskie baseny geotermalne zamiast Blue Lagoon, choć Blue Lagoon płaci lepiej, i piszemy wprost, które atrakcje nie są warte swojej ceny. Rekomendacja, która istnieje tylko dlatego, że płaci, nie jest rekomendacją.</p>
<p>Ceny, godziny i dostępność się zmieniają. Przed wyjazdem zawsze sprawdź na stronie operatora.</p>
<p>Pytania: <a href="mailto:info@touringbee.com">info@touringbee.com</a>.</p>''',
    },
}
